* Aclaración

Voy a hablar sobre la Verdad teniendo en cuenta mis experiencias
laborales e inquietudes personales. Me parece importante aclarar que
mis opiniones, reflexiones y puntos de vista están construidos desde
lo que sería una "visión del usuario". Esto es diferente a una
exposición hecha por un experto, que en este caso sería un
epistemólogo. Sin embargo, esto no es una invitación a que desprecien
mis palabras, puesto que -como veremos- la palabra de los expertos no
es la única que puede contribuir a la construcción de un campo del
conocimiento.

De todos modos, siempre es posible que algunas de mis
observaciones puedan ser consideradas superficiales, superadas o
directamente erroneas por epistemólogos o incluso por un público no
especializado. En ese caso, espero que estén atentos a señalarlo, y
espero que lo manifiesten ya sea durante la exposición o al final.

También quiero advertir que mi expectativa no es convencer a quienes
me escuchan sobre la validez de mis afirmaciones, sino que el éxito de
esta charla será el cuestionar diferentes perspectivas sobre la verdad
y sobre las ciencias, de modo que no estemos cómodos ni afirmando que
el conocimiento científico es despreciable ni encumbrándolo como a un
ídolo indiscutible.

**(sobre el final puedo retomar esto para decir que tampoco sostengo la
filosofía popular de que el punto medio entre dos extremos es siempre
mejor).**

* Mis ámbitos de trabajo.

Voy a presentar algunas ideas en relación con mis espacios de
trabajo, actuales y pasados, por lo que me parece importante para
situar a todos en el contexto en el que se desarrollan estas
reflexiones, describir brevemente estos lugares y sus características
sobresalientes, los cuales constituyen entornos donde el concepto de
verdad cobra distintos significados o tiene diferentes alcances y
particularidades.

** Enseñanza

Empecé como auxiliar-alumno en 1998, en la carrera de
Bioingeniería. Actualmente soy Jefe de Trabajos Prácticos en dos
asignaturas: Bioingeniería II y Medicina Nuclear (de acuerdo a la
nomenclatura del Plan 1993). La primera aborda las técnicas para
obtener y procesar información del mundo real y en particular del
cuerpo humano (se estudian los modos de medir la temperatura, la
presión arterial, la actividad eléctrica del corazón en la forma del
electrocardiograma, etc) mientras que la segunda se ocupa de los usos
de las radiaciones ionizantes para diagnóstico (es decir para la
obtención de imágenes del cuerpo humano) y para tratamiento
(principalmente del cancer).

** Investigación y Desarrollo

Participé en tareas de investigación en el campo de la
electrofisiología cardíaca, tanto en la Facultad de Ingeniería como en
visitas temporarias a un laboratorio de esta especialidad en Estados
Unidos.

Trabajé dentro de grupos que se ocupan de dos grandes temas:

- Uno es la variabilidad de la frecuencia cardíaca: a partir del
registro del electrocardiograma mediante electrodos superficiales se
calcula la frecuencia cardíaca, que va variando latido a latido, y se
trata de correlacionar esa información con diversos estados
fisiológicos y fisiopatológicos (como el estrés), para obtener un
índicador clínico de la condición de salud o enfermedad del
paciente.

- El otro tema es el fenómeno de excitación-contracción: se trata de
indagar en los mecanismos celulares involucrados desde que llegan los
impulsos nerviosos a las células cardíacas, hasta que éstas se
contraen, y logran en conjunto y coordinadamente que el
corazón realice su función de bomba.

**Y próximamente me voy a trabajar a un instituto del Conicet, no como
investigador, sino como "personal de apoyo" (un cargo técnico).**

*** División del campo

Las tareas de investigación "pura" y de desarrollo de tecnología están
relacionadas y se necesitan mutuamente, pero prefiero separarlas en
beneficio del abordaje del problema de la verdad.

En general las ideas más difundidas y discutidas de las diferentes
escuelas epistemológicas, desde el positivismo en adelante, se
refieren a las ciencias puras, es decir aquellas que se ocupan de
descubrir cómo es el universo, cómo funciona la naturaleza, y
demás. Para ellas se plantean y se discuten, por ejemplo, diferentes
modelos metodológicos.

El desarrollo de tecnologías o las ciencias aplicadas (que son los
viejos oficios pero profesionalizados, y que podemos llamar "ciencias
del diseño") tienen particularidades, ya que su objetivo no es tanto
comprender el mundo sino operar sobre él, mediante la creación o
modificación de procesos o instrumentos para cambiar nuestro entorno.

A la vez hay que tener en cuenta que esta diferenciación se vuelve
artificial cuando advertimos que las ciencias básicas requieren de
tecnologías más sofisticadas para permitir la realización de
experimentos, mientras que el descubrimiento de las leyes naturales
habilita al avance de la técnica.

Recordatorio de una aclaración previa: hay diversos modos de
comprender y analizar la ciencia y la tecnología. A esto me refería
cuando decía que quizás un experto epistemólogo plantearía de modo
diferente esta clasificación.

En ambos casos mi participación principal tuvo más que ver con la
construcción de instrumentos de medición para obtener información de
en cada uno de estos dos campos. No trabajé directamente en la
elaboración de teorías y experimentos, sino en posibilitar estos
últimos, pero en ambos estuve en contacto con investigadores "básicos"
y sus discusiones acerca de las incógnitas del campo de estudio, las
teorías que pretendían probar o cuestionar y los experimentos para
materializar estos propósitos.


* Primer parada: la realidad.

En todos estos ambientes las personas que encontré son realistas
duras. Asumen la existencia de una realidad objetiva, independiente de
nuestros sentidos y además dan la impresión de creer que las teorías
realmente describen la realidad tal cual es. Digo que dan esta
impresión porque nadie suele conversar sobre sus supuestos
epistemológicos; las preocupaciones científicas de los investigadores
son de otra índole (en general están preocupados por sus resultados
experimentales y en cómo conseguir fondos para continuar).

Con esto quiero decir que cuando describen un sistema, como el pasaje
de iones a través de una membrana celular, no están pensando en que se
trata de modelos que ofrecen resultados semejantes a que se perciben a
través de nuestros instrumentos y sentidos, sino que entienden que
observaciones y teorías describen a la realidad tal cual es.

Esto tiene la ventaja de que no se está permanentemente dudando de las
observaciones y de los resultados experimentales, y es posible



Hay en este problema una gran complejidad. Hay desplazamiento de
pequeños átomos cargados, llamados iones, a través de la membrana
celular y también a través de las membranas de los órganos internos
dentro de la célula, hay proteinas llamadas "canales" que dejan pasar
unos iones en particular y no otros (canales de sodio, canales de
calcio, etc), pero que afectan su funcionamiento frente a cambiantes
concentraciones de una tercer sustancia (moléculas que bloquean o
favorecen este funcionamiento), también hay otras proteinas que
funcionan como bombas (de sodio-potasio), a lo que se suma que la
estructura donde están fijadas estas proteinas tiene una consistencia
fluida, donde hay un movimiento constante de sus componentes, que a su
vez son muy dependientes de las formas para cumplir su función (un
canal es selectivo por las dimensiones que tiene su estructura, que
permite alojar un ion de sodio pero no uno de calcio). Además la
expresión de la información genética cumple un importante papel, y es
algo sobre lo cual los científicos pueden operar, puesto que
actualmente se diseñan animales de laboratorio con ciertas mutaciones
(por ejemplo la ausencia de una bomba).

Además, influyen sobre el sistema en estudio, el medio ambiente donde
se realizan las medidas, los resultados cambian cuando el tejido está
a distinta temperatura, en presencia de líquidos con distintas
concentraciones, etc.

También hay variaciones importantes en el funcionamiento del sistema
cuando se estudian las células por separado, ya que los resultados de
medir las mismas variables son distintos a cuando las mediciones se
realizan sin disgregar las células, es decir mientras estas aún están
formando parte de un órgano funcional.

La complejidad del sistema se enriquece con el agregado de
tecnologías para obtener información de los procesos que se tratan de
dilucidar. Para indagar se utilizan instrumentos y técnicas que
pueden alterar el funcionamiento de aquello que se estudia. Se
utilizan elementos para medir corrientes, temperaturas, presiones,
concentraciones, etc. Se sintetizan soluciones, se inyectan fármacos,
se realizan preparados para mantener con vida órganos aislados...

Realidad

Se pretende descubrir la realidad, es decir dilucidar el
funcionamiento de la naturaleza, respecto de la cual se tienen ciertos
supuestos: que hay una regularidad y estabilidad en la naturaleza que
se traduce en un funcionamiento bajo reglas (un canal de calcio
funciona siempre de la misma manera en condiciones semejantes). La
verdad en este contexto consiste de aquellas afirmaciones que
describen el mundo y sus procesos tal como son: el sodio ingresa por
un lugar, sale por el otro, se acumula en tal lado, genera tales
efectos, siempre! La realidad se describe con esquemas, modelos,
analogías, resultados de mediciones, fotografías, registros temporales
de la evolución de distintas variables, reglas, tablas de
probabilidades, etc.

** Ejercicio de la ingeniería. Desarrollo de tecnologías

¿es de carácter científico? (ciencias del diseño).
¿qué hago cuando me enfrento a un problema?
- multicausalidad
- complejidad

búsqueda de una racionalidad. verdad es aquello que sirve y que puedo
utilizar con cierto grado de confianza en un razonamiento.

- simulaciones
- la existencia de conocimiento no verbalizable (el perceptrón)

el imaginario sobre el quehacer del ingeniero. ¿Es realmente
matemática lo que se usa?

MEMES Ingenieriles. Buena ciencia e ingeniería vs Mala ciencia e
ingeniería.





* Realidad

Esto vendría a ser una especie de kernel o núcleo del sistema
operativo:

Parto de creer que la realidad existe y que no hay ningún genio
maligno tratando de engañarnos. Si bien la hipótesis de Matrix es
plausible, elijo no creerla. Entonces si la realidad existe la verdad
es una característica de las afirmaciones que podemos hacer sobre el
universo.

el problema de la inducción llevado al comportamiento disímil entre
células individuales y órganos

La mayoría de los ingenieros y científicos "cree" en la inducción.

Los científicos (y los ingenieros) no saben nada de los problemas de
la epistemología.

---

Puede haber caos allí donde hay reglas. La evolución de un sistema
depende de las condiciones iniciales y de las perturbaciones que
recibe (además de la estructura y función de sus partes).

---

Los argumentos como soldados. Se niega todo lo que no esté de acuerdo
con la linea principal.

---

La gente tiende a creer que los seres humanos somos máquinas que
funcionamos en un solo sentido. Creen que lo que pensamos, sentimos,
vemos, es el resultado de la expresión de la información genética y el
sinnúmero de fenómenos químicos que ocurren en nuestras células. No
faltan los papers que hablan del descubrimiento de la hormona que
genera la esperanza, el gen que causa la infidelidad, o la molécula
que causa la depresión. Pero este modelo no toma en cuenta que el
cuerpo puede ser un sistema bidireccional: nuestran sensaciones pueden
de algún modo actuar sobre nuestra química. Quizás esto tiene que ver
con el modelo de causa-efecto y con la reticencia a complejizar,
porque ya sabemos que existen montones de sistemas retroalimentados,
incluso en nuestro propio cuerpo.

programa de magia: "recursos atencionales" ¿realmente este concepto
sirve para explicar algo? es como el poder somnífero o el poder
curativo de una sustancia. / Redes. Magia y neurociencia en red.

lo que es científico es la forma de conocer, la exahustividad de la
búsqueda. no es el método, ni que se trate de algo matemático o no.

la realidad existe? puede conocerse? la ciencia se plantea que sí.

la verdad debería significar que lo que se afirma es tal como sucede
en la realidad. pero tenemos el problema de la complejidad y de la
multiplicidad de causas, y nuestra innegable limitación para
comprender. entonces tenemos que buscar sustitutos a una definición
que nos deja tan afuera. encontramos entonces esta cuestión de las
aproximaciones sucesivas, pero tiene el problema que hemos
descubierto, cada tanto nos damos cuenta de que la aproximación no
nos aproxima, como cuando la física clásica se vuelve relativista. el
cambio de paradigma es tan grande... otra definición más interesante
es la verdad como aquello que maximiza la coherencia de un conjunto
de ideas (un paradigma).
n

Cuando Franco hablaba sobre el modo "respetable" de producir
discursos (actos de habla de un cierto tipo, como en la producción
periodística de Rodolfo Walsh) remarcaba la necesidad de sostener ese
discurso en datos "objetivos de la realidad": documentos,
testimonios, estadísticas, etc. A primera vista podría parecer
parecer obvio que basta con esto. Pero podemos plantear algunas
preguntas: son todos los testimonios honestos, cómo se valoran los
datos que son contradictorios (porque la realidad no siempre se
expresa de manera coherente). Por ejemplo: los economistas, que usan y
analizan variables matemáticas y utilizan modelos computacionales,
pueden sacar conclusiones opuestas de sus estudios. Hay evidentemente
datos que es preciso desechar, como ciertas afirmaciones
gubernamentales sobre tal o cual cosa, o ciertas operaciones
periodísticas que presentan un velo demasiado endeble respecto de lo
que pretenden (no la verdad, sino otra cosa). No parece saludable
aceptar todo esto basado en la complejidad de los sistemas, porque hay
mentiras que se revelan ante el análisis. Pero hay que tener cuidado
de afirmar que siempre la realidad es cognoscible, registrable,
medible. Hay muchas interpretaciones que son necesariamente erroneas a
la luz de una inspección metódica, pero hay otras que son más
difíciles de desechar, porque aparecen ahí indicios contradictorios,
información que no es concluyente (como en el ejemplo de los
experimentos para mostrar que la tierra gira tirando una piedra desde
una torre).

Respecto de los beneficios de la ciencia, el hecho de tener
celulares, medicamentos, etc.

El problema de la falta de compromiso de los lectores y el hecho de
que no se desencadenen escándalos con consecuencias reales es también
un problema para la ciencia, si pensamos que la ciencia no debe ser
dominio exclusivo de los científicos sino de un público (ilustrado)
general. ¿Qué nos toca hacer frente a esto? Yo creo que hay que
criticar sin piedad al sistema científico, sin endiosarlo por sus
logros, y mostrar que el público general puede participar de sus
procesos, que no incluyen sólo la producción del conocimiento sino su
difusión, la participación en la selección de problemas relevantes,
la auditoría de las instituciones, etc. Por eso es importante una
educación que permita a las personas participar adecuadamente en
estas tareas.

Algo que me parece imprescindible para el espíritu científico es
advertir las debilidades de las propuestas que uno hace, de las
teorías que uno tiene. Recibir la crítica y evaluarla y no empezar
por ridiculizarla, sino por tratar de entender desde la óptica del
otro. Muchas veces esto puede conducir igual a reafirmar lo que uno
piensa, pero quizás no siempre. Se puede aprender de puntos de vista
no expertos o no especializados (por ejemplo en quienes pueden
elaborar sistemas de comprensión basados en el uso de
analogías). Todas las tradiciones pueden aprender de otras, unas
disciplinas pueden aprender de otras, de otras culturas y formas de
pensamiento. La realidad es tan rica que quizás tiene aspectos que no
son binarios, en los que podrían ser aplicables lógicas diversas. O
hay que advertir que el binarismo es posible siempre que permita
cierta flexibilidad (¿qué onda con los sexos, no es acaso absurdo
plantear la pregunta sobre si una persona es mujer o varón?).

Es necesaria una riqueza del lenguaje para poder comprender el mundo.

Les preocupa el problema de la objetividad.

Sistemas complejos, caos, predicción. ¿Sabemos cuál es el efecto de
una sustancia sobre el cuerpo? ¿Cómo discutimos si el g

La comprensión parcializada de la realidad por parte de los
científicos. La búsqueda de un lenguaje común derivó en lo que hoy es
la microespecialización. ¿Pueden entenderse realmente dos científicos
de la misma disciplina que estudian fenómenos diversos? Cómo esta
especialización atenta contra la comprensión holística de la realidad.

De Feyerabend: pg4. En respuesta a si es deseable apoyar la ciencia
como único camino para comprender el mundo, responde que no y que hay
dos razones para ello: "La primera consiste en que el mundo que
deseamos explorar es una entidad en gran medida desconocida. Debemos
por tanto mantener abiertas nuestras opciones y no restringirlas de
antemano. ... ¿Quién garantiza que [las prescripciones
epistemológicas] constituyan el mejor camino para descubrir, no ya
unos cuantos "hechos" aislados, sino ciertos secretos profundos de la
naturaleza? La segunda es que una educación científica como la
descripta antes (y como se imparte en nuestras escuelas) no puede
reconciliarse con una actitud humanista".

Me gustó la definición de que verdad es la predisposición a la
búsqueda de quien investiga, y no es una propiedad en sí de la
teoría.

Lo científico es la predisposición a la investigación, a la búsqueda
de verdades, el inconformismo con el nivel de conocimiento actual, la
apertura a la discusión, ...

A veces la discusión es entre ciencia vs no-ciencias, cuando la
dicotomía más peligrosa es buena ciencia vs mala ciencia.

la verdad tiene capas, como una cebolla. las capas externas de la
teoría atómica permiten explicar el funcionamiento de las bombas de
cobalto, aún cuando se utilicen modelos completamente superados y
notoriamente falsos. la analogía tiene el problema de que uno puede
tender a considerar que a capas más profundas hay mayor contenido de
verdad, cuando en realidad distintas teorías en distintas capas
pueden articular una visión del mundo mejor que una sola capa interna.

Pensemos en el sistema científico y en cómo su producción no
solamente sirve para brindarnos celulares y vehículos a precio
accesible, sino una batería de muletas para el modo de producción
capitalista.

Después está el problema de usar un lenguaje suficientemente bueno
para describir un proceso. Se puede caer en el error de evaluar el
sistema educativo basando el juicio en ciertos valores estadísticos,
cuando los mismos no representan la realidad de lo que pasa dentro de
un aula.

Feyerabend plantea que los niños no aprenden sólo por la
argumentación durante la enseñanza, sino a "un proceso de crecimiento
que se desarrolla con la fuerza de una ley natural. Y donde los
argumentos parecen tener efecto, éste se debe más a menudo a su
repetición física que a su contenido semántico. Después de admitir
todo esto, hemos de aceptar también la posibilidad de crecimiento
no-argumentativo en el adulto... debería esperarse que los cambios
catastróficos del contorno físico, las guerras, el colapso de los
sistemas de moralidad imperante, o las revoluciones políticas, habrán
de transformar también los modelos de reacción del adulto, incluidos
importantes modelos de argumentación. Esta transformación puede ser
también un proceso completamente natural, y la única función de la
argumentación racional quizás radique en aumentar la tensión mental
que precede y **causa** la explosión de la conducta.

Ahora bien, si son los eventos, no necesariamente los argumentos, la
causa de que adoptemos nuevos criterios, incluyendo formas nuevas y más
complejas de argumentación ¿no es cierto que los defensores del statu
quo tendrán que aducir no sólo contra-argumentos, sino causas
contrarias? ("la virtud sin el terror es ineficaz", dice Robespierre).
Y si las viejas formas de argumentación resultan demasiado débiles
para constituir una causa, ¿no deberán estos defensores o bien
abandonar, o bien recurrir a medios más fuertes y más irracionales?
(Es muy dificil(Pg 8-9).

cómo se distribuye el dinero en ciencias? qué campos reciben más, qué
lineas de investigación se apoyan más?

Tenemos la sensación, al estudiar ciencias, por el modo en que se
presentan los conocimientos, de que las distintas disciplinas
tuvieron un progreso continuo y sus teorías conforman un cuerpo
explicativo coherente, sin fisuras. Nunca se mencionan las
observaciones que cuestionan las teorías, ni cómo se dieron los
conflictos cuando teorías opuestas se encontraban en disputa.

Sobre la sustitución de teorías: El progreso se consigue a menudo por
medio de una crítica desde el pasado... Después de Aristóteles y
Ptolomeo, la idea de que la Tierra se mueve -esa extraña, antigua, y
"completamente ridícula" concepción pitagórica- fue arrojada al
montón de escombros de la historia, para ser revivida sólo por
Copérnico y para convertirse en sus manosen un arma con la que vencer
a los vencedores de dicha concepción. (Pg 33) En esto quizás puedo
plantear una analogía entre el "viejo" Lisp y los modernos lenguajes
de computación (o por ejemplo las modas de la programación orientada
a objetos y la programación funcional). Sigue Feyerabend: "Semejantes
desarrollos no son sorprendentes. Una idea no se examina nunca en
todas sus ramificaciones y ningún punto de vista recibe jamás todas
las oportunidades que se merece. Las teorías se abandonan y
sustituyen por otras explicaciones más de moda, mucho antes de tener
la oportunidad para mostrar sus virtudes.

Cita de Einstein, Fey. Pg 41 (nota al pie) "Es realmente extraño que
los hombres sean, por lo general, insensibles a los más fuertes
argumentos mientras que siempre están inclinados a sobrevalorar la
exactitud de las mediciones." (podría buscar cosas sobre la oposición
entre físicos teóricos y físicos experimentales)

La idea de que el conocimiento para vivir mejor ya está..

pensar sobre las dos teorías sobre el registro del ecg. cuál es
veradadera?

lo que puedo plantear es que el pragmatismo es la medida de la
verdad, pero que éste (el pragm) tiene sus límites, nos va a impedir
conocer ciertas cosas.

el recorte de las disciplinas es artificial, eso se nota en la
formación de los científicos de areas que incluyen campos diversos,
como la biofísica. En estos campos es que se vuelve notoria la
necesidad de una visión más holística, ya que los fenómenos no pueden
comprenderse utilizando los conceptos de una sola disciplina.
