* Aclaración

Voy a hablar sobre la Verdad teniendo en cuenta mis experiencias
laborales e inquietudes personales. Me parece importante aclarar que
mis opiniones, reflexiones y puntos de vista están construidos desde
lo que sería una "visión del usuario". Esto es diferente a una
exposición hecha por un experto, que en este caso sería un
epistemólogo. No voy a citar a Habermas, ni a Hegel, ni a Marx. Sin
embargo, esto no es una invitación a que desprecien mis palabras,
puesto que -como veremos- la palabra de los expertos no es la única
que puede contribuir a la construcción de un campo del conocimiento.

De todos modos, siempre es posible que algunas de mis
observaciones puedan ser consideradas superficiales, superadas o
directamente erroneas por epistemólogos o incluso por un público no
especializado. En ese caso, espero que estén atentos a señalarlo, y
espero que lo manifiesten ya sea durante la exposición o al final.

También quiero advertir que mi expectativa no es convencer a quienes
me escuchan sobre la validez de mis afirmaciones, sino que el éxito de
esta charla será el cuestionar diferentes perspectivas sobre la verdad
y sobre las ciencias, de modo que no estemos cómodos ni afirmando que
el conocimiento científico es despreciable ni encumbrándolo como a un
ídolo indiscutible.

Otra cosa a tener en cuenta es que en el contexto de una interminable
oposición con filosofías y organizaciones oscurantistas, desde el
Estado Islámico que impone la Sharia a sangre y fuego en Irak y Siria,
hasta las organizaciones censuradoras que pretenden imponer la censura
global controlando internet, es preciso decir que estamos del lado de
libertad, de la ilustración, de la racionalidad y de la oposición a
todo oscurantismo. El propósito de esta charla, en cambio, tiene que
ver con cuestionar lo que hay de oscuro en donde debería primar la luz.

**(sobre el final puedo retomar esto para decir que tampoco sostengo la
filosofía popular de que el punto medio entre dos extremos es siempre
mejor).**

* Mis ámbitos de trabajo.

Voy a presentar algunas ideas en relación con mis espacios de
trabajo, actuales y pasados, por lo que me parece importante para
situar a todos en el contexto en el que se desarrollan estas
reflexiones, describir brevemente estos lugares y sus características
sobresalientes, los cuales constituyen entornos donde el concepto de
verdad cobra distintos significados o tiene diferentes alcances y
particularidades.

** Enseñanza

Empecé como auxiliar-alumno en 1998, en la carrera de
Bioingeniería. Actualmente soy Jefe de Trabajos Prácticos en dos
asignaturas: Bioingeniería II y Medicina Nuclear (de acuerdo a la
nomenclatura del Plan 1993). La primera aborda las técnicas para
obtener y procesar información del mundo real y en particular del
cuerpo humano (se estudian los modos de medir la temperatura, la
presión arterial, la actividad eléctrica del corazón en la forma del
electrocardiograma, etc) mientras que la segunda se ocupa de los usos
de las radiaciones ionizantes para diagnóstico (es decir para la
obtención de imágenes del cuerpo humano) y para tratamiento
(principalmente del cancer).

** Investigación y Desarrollo

Participé en tareas de investigación en el campo de la
electrofisiología cardíaca, tanto en la Facultad de Ingeniería como en
visitas temporarias a un laboratorio de esta especialidad en Estados
Unidos.

Trabajé dentro de grupos que se ocupan de dos grandes temas:

- Uno es la variabilidad de la frecuencia cardíaca: a partir del
registro del electrocardiograma mediante electrodos superficiales se
calcula la frecuencia cardíaca, que va variando latido a latido, y se
trata de correlacionar esa información con diversos estados
fisiológicos y fisiopatológicos (como el estrés), para obtener un
índicador clínico de la condición de salud o enfermedad del
paciente.

- El otro tema es el fenómeno de excitación-contracción: se trata de
indagar en los mecanismos celulares involucrados desde que llegan los
impulsos nerviosos a las células cardíacas, hasta que éstas se
contraen, y logran en conjunto y coordinadamente que el
corazón realice su función de bomba.

**Y próximamente me voy a trabajar a un instituto del Conicet, no como
investigador, sino como "personal de apoyo" (un cargo técnico).**

*** División del campo

Las tareas de investigación "pura" y de desarrollo de tecnología están
relacionadas y se necesitan mutuamente, pero prefiero separarlas en
beneficio del abordaje del problema de la verdad.

En general las ideas más difundidas y discutidas de las diferentes
escuelas epistemológicas, desde el positivismo en adelante, se
refieren a las ciencias puras, es decir aquellas que se ocupan de
descubrir cómo es el universo, cómo funciona la naturaleza, y
demás. Para ellas se plantean y se discuten, por ejemplo, diferentes
modelos metodológicos.

El desarrollo de tecnologías o las ciencias aplicadas (que son los
viejos oficios pero profesionalizados, y que podemos llamar "ciencias
del diseño") tienen particularidades, ya que su objetivo no es tanto
comprender el mundo sino operar sobre él, mediante la creación o
modificación de procesos o instrumentos para cambiar nuestro entorno.

A la vez hay que tener en cuenta que esta diferenciación se vuelve
artificial cuando advertimos que las ciencias básicas requieren de
tecnologías más sofisticadas para permitir la realización de
experimentos, mientras que el descubrimiento de las leyes naturales
habilita al avance de la técnica.

Recordatorio de una aclaración previa: hay diversos modos de
comprender y analizar la ciencia y la tecnología. A esto me refería
cuando decía que quizás un experto epistemólogo plantearía de modo
diferente esta clasificación.

En ambos casos mi participación principal tuvo más que ver con la
construcción de instrumentos de medición para obtener información de
en cada uno de estos dos campos. No trabajé directamente en la
elaboración de teorías y experimentos, sino en posibilitar estos
últimos, pero en ambos estuve en contacto con investigadores "básicos"
y sus discusiones acerca de las incógnitas del campo de estudio, las
teorías que pretendían probar o cuestionar y los experimentos para
materializar estos propósitos.


* Primer parada: la realidad.

En estos ambientes las personas que encontré son realistas duras, que
asumen la existencia de una realidad objetiva, independiente de los
sentidos. La mayoría, sino todos, creen que la realidad es tal cual la
registramos con nuestros instrumentos, realidad que vamos
comprendiendo cada vez mejor mediante teorías que son progresivamente
explicativas (es decir que no son instrumentalistas).

En este ambiente la realidad se analiza a través de los datos que se
acopian durante experimentos. Estos experimentos se diseñan para
obtener información útil sobre un proceso. Para ello se tratan de
establecer con precisión condiciones controladas para que la
información obtenida pueda ser analizada en busca de relaciones entre
variables, dependencia con ciertos parámetros, relaciones de
causalidad y cosas por el estilo. También se realizan experimentos
para ver el mismo fenómeno con diferentes técnicas, lo cual puede
ofrecer información nueva. Si el planteo de un experimento fuera
caótico, o si estuviese diseñado inadecuadamente, los resultados no
permitirían concluir nada. La realidad se describe con esquemas,
modelos, analogías, resultados de mediciones, fotografías, registros
temporales de la evolución de distintas variables, reglas, tablas de
probabilidades, etc.

Para los científicos si un fenómeno ocurre tiene una o varias causas y
distintos efectos, y no tiene mucho sentido realizar suposiciones que,
a la luz de nuestros saberes actuales, resulten irracionales si se
pretende cierta eficiencia en el proceso de develar lo desconocido. Si
hay que explicar cómo se limita la cantidad de iones de calcio que
ingresan a la célula cardíaca cuando llega un impulso nervioso, una
explicación relacionada con las fuerzas sutiles del lado oscuro o con
la memoria cuántica de la flecha del tiempo obviamente que sería
impublicable, salvo en revistas literarias. El canal de calcio
funciona siempre de la misma manera en condiciones semejantes y hay
ciertas limitaciones en cuanto a las variables a las cuales podemos
atribuir participación en el fenómeno, de acuerdo al conocimiento
actual.

No hay en este esquema de trabajo lugar para afirmaciones relativistas
extremas, tales como que es válida cualquier interpretación laxa de
los resultados obtenidos. Primero por la suposición realista de que la
naturaleza funciona de alguna forma coherente y regular (incluyendo
los fenómenos probabilísticos y caóticos que también presentan rasgos
de coherencia y regularidad), y segundo por la evaluación a la que es
sometida la investigación y de la cual depende su aceptación y
posibilidad de continuidad. Si bien se acepta que las teorías tienen
diverso grado de aproximación a la realidad, y se entiende que los
modelos pueden mejorarse, no se advierten estas salvedades en el
lenguaje cotidiano.

La verdad, en este contexto, consiste de aquellas afirmaciones que
describen el mundo y sus procesos. La realidad se describe con
teorías, esquemas, modelos, ecuaciones, fotografías, registros
temporales de la evolución de distintas variables, tablas de
probabilidades, etc.  Debe haber un acuerdo ajustado entre las
predicciones derivadas de las teorías y las observaciones realizadas
en condiciones experimentales. Los jueces de esta verdad son los
pares, principalmente los revisores de los artículos que aparecen en
las revistas especializadas y también los evaluadores en las
instituciones que otorgan el presupuesto para continuar las
investigaciones.

* Segunda parte: problemas de una visión demasiado ingenua

La descripción que vengo haciendo muestra cómo se pretende depurar el
conocimiento de charlatanería y cómo se intenta establecer
conocimientos sólidos que permiten el avance en la comprensión del
universo.

Pero vamos a plantear algunas dificultades. En primer lugar pareciera
que no hay mucho lugar para la contradicción, o que éstas son
facilmente eliminables en base a la experimentación y a la
contrastación intersubjetiva por parte de la comunidad de pares.

Sin embargo los resultados experimentales no siempre son fáciles de
analizar. A veces la información dice una cosa en un conjunto de
experimentos y otra muy distinta al analizar iguales experimentos
realizados en las mismas condiciones, y no se sabe de dónde proviene
la divergencia. ¿Hubo algún error en la concentración de una solución?
¿Hubo problemas con el instrumental de registro?  ¿Estuvo la persona
encargada del experimento realmente atenta y anotó todo lo ocurrido?
¿El tejido donde se realizó el registro se preparó sin causarle daños?
Muchas cosas pueden salir mal y suele destinarse mucho tiempo a
depurar los experimentos, ajustar los instrumentos para que su
funcionamiento sea sólido, consistente, inmune a las perturbaciones.

Cuando de la experimentación en relación con un problema disciplinar
se obtienen resultados divergentes, al utilizar las mismas
herramientas o cuando se ponen en juego distintas metodologías (pero
siempre sobre el mismo proceso), el motivo puede estar en que
efectivamente se estén produciendo errores sistemáticos en la
metodología empleada (es decir que se pueden solucionar respondiendo a
las preguntas que hacía antes) o puede ser que la evidencia sea
efectivamente caótica porque el sistema que se analiza tiene una
complejidad tal que pequeñas variaciones en un parámetro producen
grandes efectos, o quizás la presencia de una variable desconocida
tiene una influencia que no podemos advertir, o incluso puede ser que
la teoría que subyace a nuestras observaciones no nos permite valorar
adecuadamente lo que observamos. Y estos son los únicos problemas que
pueden aparecer.

Para ilustrar esto voy a comentar brevemente el ejemplo más
paradigmático respecto de la oposición entre ciencia y religión. Desde
el s IV ac hasta el siglo XVI se mantuvo mayoritariamente aceptado el
modelo geocéntrico propuesto por Ptolomeo y Aristóteles, el cual
contaba con la bendición de la Iglesia Católica y su eficaz máquina
propagandística, incluyendo la técnica publicitaria conocida como
Inquisición (ja). Durante el Renacimiento, Galileo construye varios de
los primeros telescopios (aunque no es su inventor) y realiza
observaciones (como por ejemplo de las lunas de Saturno) que permiten
cuestionar el modelo geocéntrico. A pesar de que conocemos el
desenlace, y sabemos que la teoría geocéntrica es incorrecta, voy a
utilizar el ejemplo para mostrar que las observaciones de Galileo y de
sus oponentes no eran necesariamente evidentes, obvias y fáciles de
aceptar. Con esto pretendo mostrar cómo el relato simplificado de los
hechos que lleva a colocar en el lugar del absurdo las posiciones
geocéntricas le otorgan al empirismo una fortaleza inmerecida.

Hay al menos dos aspectos del problema que me gustaría plantear:

Los conocimientos de óptica de Galileo no eran suficientes para que
resultaran incuestionables las observaciones hechas con el
telescopio. Una cosa es que se pudiera comprobar que con este nuevo
instrumento se podía ampliar una imagen conocida dentro de la Tierra,
y otra es que pudiese funcionar de manera confiable para observar
objetos celestes. Por ejemplo: ¿era posible entender qué significaban
las distorsiones de los sistemas primitivos de lentes o sospechar el
efecto de la refracción en la atmósfera terrestre? ¿Pensamos que los
telescopios de Galileo ofrecían una calidad de imagen comparable al
telescopio de la Asociación Entrerriana de Astronomía?  Gran parte de
la física óptica necesaria para comprender el telescopio no estaba al
alcance de Galileo y fue desarrollada después. Además las
observaciones eran inconexas también con las predicciones de la teoría
copernicana, por ejemplo el hecho de que las dimensiones de los
planetas a lo largo de su órbita no coincidían con las diferencias que
anticipaba esta teoría. Para plantear una analogía podríamos sustituir
el instrumento "telescopio" por el instrumento "Wikipedia". Si no
supiésemos cómo funciona quizás empezamos a usarla para buscar ciertas
definiciones y vemos que los resultados que nos ofrece coinciden con
información que ya conocíamos o que previamente buscamos en otra
enciclopedia. ¿Alcanza con eso para confiar en que toda la información
que en adelante busquemos en Wikipedia será veraz?  Por supuesto que
no, y esto no quiere decir que la información de la Wikipedia no sirva
para nada. Podemos resumir todo esto afirmando que la observación no
es independiente de la teoría, que lo que observamos está condicionado
por lo que sabemos. Otro ejemplo: imágenes obtenidas del cuerpo humano
mediante rayos X, tomografía computada, resonancia magnética,
tomografía de emisión de positrones y demás, nos brindan información
que no todos estamos en condiciones de interpretar y además, aquellos
que sí lo están, no siempre pueden efectuar lecturas carentes de
errores a partir de ellas. Siempre hay una interrelación entre
observación y teoría, lo cual vuelve dificil aceptar que haya
posibilidad de efectuar observaciones puras que puedan fortalecer o
debilitar puntos de vista en conflicto. En el lenguaje de la
epistemología se suele decir que las observaciones están imbuidas de
teoría.

En segundo lugar, volviendo al ejemplo de Galileo, se puede afirmar
que había elementos empíricos también en el campo de los
aristotélicos. Por ejemplo: para sostener que la Tierra no se movía
planteaban el siguiente experimento. Si se deja caer una piedra desde
una torre muy alta y la Tierra se mueve, sería razonable que la piedra
no cayese sobre la base de la torre, sino a una distancia igual a la
distancia recorrida por la Tierra durante el tiempo en que se produjo
la caida. Otro argumento en el mismo sentido: si dos proyectiles se
lanzan en direcciones opuestas con la misma fuerza, deberían recorrer
distinta distancia. Faltaba la noción de inercia, para explicar estos
dos hechos contradictorios con la tesis heliocéntrica. Lo que muestran
estos ejemplos es que la obviedad de una hipótesis recién se logra
mucho tiempo después de que teorías opuestas diferentes disputan cuál
es aquella con mayor contenido de verdad.  Con esto podemos apreciar
que cuando el conocimiento trata de expandirse sobre terreno
desconocido se enfrenta con desafíos que no son tan triviales como lo
proponen positivistas y falsacionistas. Quizás estas reflexiones nos
permitan esquivar el peligro de convertirnos en dogmáticos defensores
del empirismo.

Para un estudio detallado de cómo se dio la conversión del
geocentrismo al heliocentrismo se puede leer "Tratado contra el
método" de Paul Feyerabend.

En conclusión, la contrastación empírica parece cobrar más fuerza
cuando ya se ha desarrollado la teoría, y cuando no se trata solamente
de un solo tipo de observación sino que ya existe un entramado de
argumentos que fortalecen un modelo explicativo.

(No se si hablé ya de que las teorías son verdaderas siempre bajo
contextos limitados, por ejemplo las leyes de la física clásica para
objetos moviéndose a velocidades mucho menores a la velocidad de la
luz).

** La verdad en los sistemas complejos. Especialización y Holismo.

La verdad de una afirmación científica tiene que ver con la adecuación
a la realidad. Pero hay distintos niveles de verdad en el
conocimiento. Cuando se trabaja sobre un sistema complejo, se pueden
hacer afirmaciones verdaderas, pero que no tienen mucho contenido
descriptivo o explicativo, o son limitadas en cuanto a que permiten
comprender elementos parciales de un sistema pero no alcanzan para
entender que sucede a nivel global. Esto no quiere decir que las
verdades limitadas sean despreciables, pero nos advierte sobre los
alcances de los saberes que tenemos.

Para estudiar el fenómeno de excitación-contracción hay muy diversas
técnicas y aproximaciones. Se pueden realizar mediciones eléctricas u
ópticas, con preparados de células aisladas o sobre porciones de
tejido o incluso en corazones enteros, sobre diversos modelos
animales: ratón, conejo, rata, cerdo, etc. Algunos métodos se utilizan
mucho porque son relativamente fáciles de utilizar, o porque el éxito
de alguna investigación les dio impulso y se popularizaron. Pero
justamente ocurre lo siguiente: los resultados obtenidos son
contradictorios. Lo que sucede en la célula aislada es diferente a lo
que sucede en el corazón completo, y por lo tanto, lo que se descubre
sobre los mecanismos en un nivel de organización celular no es tan
fácil de extrapolar para comprender lo que sucede en el órgano
completo. No quiere decir que lo que averiguamos tras fraccionar el
sistema es inútil, sino que es limitado lo que podemos saber si sólo
hacemos estudios analíticos.

Esto que sucede a nivel celular y tisular se amplifica cuando tratamos
de comprender los macrosistemas. Al considerar el cuerpo completo de
una persona es indeterminada la cantidad de variables
interrelacionadas que tienen efecto sobre la porción del cuerpo que
pretendemos investigar. Es necesario un estudio de las partes, pero el
funcionamiento de la totalidad no es solamente la suma del
funcionamiento de las individualidades. En el sistema completo
(obviamente cuando hablo de sistemas también me refiero a sistemas
sociales) se dan interacciones múltiples y complejas que modulan el
comportamiento de los componentes individuales. En este sentido me
parece que hay que atenuar el entusiasmo por los resultados de la
investigación científica basada en la especialización. No es tampoco
fácil pensar en un modo de producción de conocimientos más holístico e
interdisciplinario que no caiga en la improductividad.

Había una clave importante en la pretensión de desarrollar un lenguaje
único para la ciencia. Hoy en día el camino equivalente es el de
conformar equipos de investigación que integren los saberes de
distintas disciplinas, dado que un mismo fenómeno debe observarse y
estudiarse desde distintas perspectivas para descubrir verdades de
mayor profundidad. La matemática es un lenguaje que se pensó que puede
ser compartido por distintas disciplinas y servir de medio objetivo
para la descripción del mundo. Yo creo que la matemática es un
lenguaje útil para ciertas cosas y que hay otros lenguajes que se
ajustan mejor para describir ciertos fenómenos. ESCRIBIR EJEMPLO DE
LAS ESTADISTICAS EDUCATIVAS.


** La verdad como un entramado autocoherente.

Hay una imagen que no quiero dejar de comentar acerca de cómo imaginar
la verdad en nuestras concepciones sobre el mundo. Quizás en algunos
casos cuando los sistemas que estudiamos son menos complejos,
efectivamente podamos pensar que la verdad describe a la realidad tal
cual es. Pero en los sistemas más complejos e interesantes este ajuste
me parece deseable pero dificultoso de lograr. Es más razonable pensar
que las verdades que podemos producir tienen puntos de contacto con la
realidad pero parte de nuestras afirmaciones sólo son verdad en tanto
mejoran la coherencia del modelo explicativo (esto sería como una
postura instrumentalista) y no necesariamente estén éstas "verdades"
tan ajustadas a la realidad verdadera. Verdades, entonces, serían
aquellas afirmaciones que tiendan a que el modelo explicativo sea cada
vez más autocoherente, como si estuviésemos construyendo una tela de
araña donde sus puntos de apoyo fuesen aquellas comprobaciones
empíricas que nos muestran el ajuste a la realidad, mientras que
teorías y otras construcciones de la explicación sirviesen para
fortalecer la estructura de la tela de araña, aún cuando no
necesariamente brinden muestras inequívocas de estar vinculadas con la
realidad.

* La verdad en el ámbito de la tecnología o de las ciencias del diseño

La función más interesante de los ingenieros es actuar sobre la
realidad para dar respuesta a alguna necesidad humana (o del
mercado). Los bioingenieros con tareas más específicamente técnicas,
como los que se ocupan del mantenimiento de hospitales y clínicas, o
del diseño de instrumentos utilizados en el cuidado de la salud,
dependen de los conocimientos y teorías de las distintas
disciplinas. Es obvio que una mayor comprensión de los fenómenos
físicos y biológicos fortalece las posibilidades de tener éxito al
diseñar nuevos instrumentos, o al identificar fallas, o al controlar
procesos.

Sin embargo, hay tecnologías que producen conocimiento sobre el mundo
sin pretensión de realidad. Esta característica de volverse generadora
de conocimientos difumina el límite entre ciencia y tecnología, y
aleja la concepción de tecnología como una mera aplicación del
conocimiento científico. Mediante la tecnología se pueden construir
representaciones parciales de la realidad, es decir sistemas
artificiales que modelan un aspecto del mundo real, que nos brindan
información aún cuando la estructura y los fenómenos internos del
sistema real nos sigan siendo desconocidos. En otras palabras podemos
decir que a través de la tecnología se construye un conocimiento
instrumental del mundo.

Puedo dar un ejemplo con la intención de ilustrarlo:

Se puede elaborar un conjunto de ecuaciones diferenciales que
representan el funcionamiento del sistema cardiovascular y gracias a
ellas saber cómo será la distribución de la presión en el corazón y en
las arterias y venas, o cómo variará el volumen de las cavidades del
corazón a lo largo del tiempo, pero esto sin hacer ninguna referencia
a las células, a las proteinas de la sangre, a la información
genética, etc. Es decir, desconociendo olímpicamente a los fenómenos
físicos y biológicos que subyacen y que son responsables de este
funcionamiento.

Ahora bien, debe haber verdad y validez en las predicciones que se
desprenden de los modelos y simulaciones. Las predicciones del modelo
se contrastan con mediciones realizadas sobre el sistema real, de modo
tal que sólo resulta aceptable el modelo en tanto ofrezca resultados
coincidentes con las lecturas obtenidas a partir del sistema
real. Recién una vez que se comprueba que el sistema artificial es
capaz de representar al sistema real de algún modo (con ecuaciones
deterministas, con funciones de probabilidad, o con sistemas análogos
-por ejemplo los modelos eléctricos o neumáticos del sistema
cardiovascular), recién a partir de allí se vuelve admisible de
utilizar como herramienta.

Sin embargo hay que advertir que el modelo puede haber sido probado
exitosamente bajo distintas condiciones: considerando arterias con
paredes más o menos elásticas, con volúmenes ventriculares mayores o
menores, etc. De este modo tenemos un cierto grado de confianza en
este modelo, pero esto no significa que las ecuaciones puedan predecir
la evolución del sistema siempre y para cualquier condición. El
sistema real, dada su complejidad, nunca puede ser descripto
completamente.

Otro elemento que complica las predicciones es la naturaleza aleatoria
de ciertos procesos. Podemos saber qué probabilidades hay de que un
nucleo de una sustancia radiactiva decaiga en un momento dado, pero no
tenemos certeza respecto del momento exacto en el que esto
efectivamente habrá de suceder. Es decir, podemos predecir el
comportamiento promedio de un conjunto de átomos, pero carecemos de
certeza para predecir qué sucederá con cada uno de estos átomos a lo
largo del tiempo.

** Incertidumbre

En ingeniería el error es imposible de erradicar. Si tenemos en cuenta
que necesitamos registrar el mundo real antes de actuar sobre él,
puede parecer catastrófico que no podamos determinar la realidad sin
cometer errores.

Sin embargo el problema se aborda tratando de reducir estos errores y
cuantificando las incertidumbres. En algunos casos el avance del
conocimiento científico y de los desarrollos tecnológicos permite
efectivamente disminuir estos errores, aunque sin eliminarlos
completamente.

Pero en muchos casos hay un problema insalvable, puede suceder que la
propia variable que se pretende medir no tenga un valor exacto, o que
ese valor sea indeterminable, como en el caso de la ubicación y la
velocidad de una partícula sub-atómica.

¿De dónde proviene esta limitación a la exactitud con que se puede
registrar la realidad? Vamos a usar un ejemplo para mostrarlo. En la
era de los GPS no parece deparar ningún contratiempo determinar la
distancia entre dos ciudades, por ejemplo entre Paraná y Santa
Fe. ¿Hay 30, 35 km?  Puede ser, pero si decidimos no creerle a los
carteles de la ruta y nos proponemos que cada uno de nosotros viaje en
algún vehículo para obtener una medida de la distancia a partir de la
lectura del cuentakilómetro, ¿vamos a llegar todos al mismo resultado?
Cada uno puede hacer el experimento con leves diferencias: ¿cuál
considerará cada uno que es el punto de partida y el punto de llegada?
¿La plaza principal de cada ciudad? ¿El límite según la legislación?
¿La ubicación de las casas más cercanas entre ambas ciudades? Por otro
lado, ¿habrán tomado todos el mismo camino y se habrán desplazado
todos por la trayectoria exacta que recorrieron los demás? Obviamente
que si nos reunimos para comparar resultados nuestras medidas serán
distintas, aún cuando todos contemos con un cuentakilómetros de gran
calidad. La propia variable que queremos medir es hasta cierto punto
indeterminada, excepto que todos acordemos un criterio, de modo que la
variable ya no existe sólo en la realidad sino que la hemos definido
en nuestro lenguaje, es decir que la hemos manipulado y ya no es ajena
a nuestra existencia. Quizás uno puede pensar que esto es un caso
particular, ¿y si el objeto que queremos medir es una mesa?
Aparentemente no tendremos la dificultad que acabamos de señalar para
las ciudades, pero si queremos tener muy alta precisión en nuestra
medida y no nos alcanza con usar una lupa en cada extremo y
amplificamos más y más los bordes, entonces ya no vamos a ver una
superficie que se interrumpe abruptamente, sino que vamos a poder ver
los átomos de la mesa, y sus nubes electrónicas que además se van a
estar moviendo porque incluso en los sólidos hay agitación térmica.

Tenemos que preguntarnos si efectivamente podremos desprendernos de
estas incertidumbres o si podemos convivir con ellas. La distancia de
Paraná a Santa Fe nos puede servir si queremos calcular cuánto
combustible tener en el tanque (podríamos preguntarnos: ¿cuánta nafta
exactamente consume nuestro vehículo por kilómetro?), o si necesitamos
saber en cuánto tiempo podemos hacer el viaje. En el contexto de esos
problemas, que la distancia varíe en uno, dos o cinco kilómetros no
tiene demasiado impacto. Hay un grado de incertidumbre tolerable en el
conocimiento de la realidad que no afecta nuestra capacidad de actuar
sobre ella. Si queremos saber cuántas personas pueden sentarse
alrededor de la mesa, no tiene sentido tratar de obtener una medida
con la precisión de un Angstrom.

De todos modos creo que este es un tema interesante porque muchas
veces se apela a la ciencia para tratar de resolver temas
conflictivos, y perdemos la noción de que la ciencia no puede
responder cualquier pregunta. Pongamos por caso el tema de la vida
humana: ¿cuando comienza y cuando termina? ¿En qué momento se inicia
la existencia de un ser humano y en qué momento finaliza? Estas
preguntas también requieren criterios compartidos para poder ser
respondidas.

Lo interesante igual es advertir entonces que quizás la realidad puede
ser medida, comprendida, manipulada, hasta cierto punto. Como si se
tratase de una cosa que aún cuando afinamos nuestros sentidos se
presenta con bordes borrosos. Esto no quiere decir que de lo mismo
cualquier número para representar la realidad. Las medidas que los
ingenieros deberían usar (aunque muchas veces se pase por alto) se
escribe con notación de intervalos: la medida se expresa como un punto
medio con una incertidumbre hacia ambos lados: la mesa mide 1,20 mas
menos 1 cm. Estamos seguros de que la mesa mide entre 1,19 y
1,21. Ahora pasó algo interesante, pasamos a tener total certeza de
que la medida es algún valor dentro de ese rango.

* Enseñanza



** Científicos poco científicos

Diferencia entre la ciencia y las instituciones científicas

O también: se puede tener unmodelar con ecuaciones un fenómeno y aún así no
comprender el fenómeno en sí, pero pesar de esta carencia igual se
logra obtener suficiente información para poder actuar. Es decir,
podemos elaborar sistemas artificiales que representan el
funcionamiento de los sistemas naturales, a pesar de que la estructura
con la cual están construidos sea absolutamente diferente.



La ciencia no dice si la energía nuclear es segura o no es segura. Ni
si el glifosato es o no seguro. Lo que nos indica es el riesgo que
tiene cada una. Nos puede mostrar alternativas o la falta de
ellas. Pero no es la ciencia la que tiene que aprobar o no
algo. Porque cuando decimos que la ciencia aprueba o no algo lo que
estamos diciendo es que las instituciones científicas lo hagan. Y como
las instituciones científicas son una construcción humana atravesada
por intereses políticos y económicos, podemos tener a los científicos
del Conicet coincidiendo con Lino Barañao respecto de la inocuidad de
los procesos productivos de Monsanto, Barrick Gold, Botnia y Chevrón.

Mi conclusión es que lo único científico no es el método sino la
voluntad de saber a través de la razón.

comprender y explicar

complejidad: ejemplo de los efectos del glifosato

El problema de que la enseñanza sea a-histórica es que en muchos casos
no conocemos las teorías rivales ni tampoco los problemas que
tuvieron que superar.


Podemos
construir un sistema artificial que muestre cómo es la evolución de la
temperatura de un cuerpo, a pesar de que lo hagamos con ecuaciones a
partir de las cuales no podemos explicar cómo es que se realiza
físicamente la transferencia de calor. Esta es la función de los
modelos y de las simulaciones.

En algunos casos, pueden sintetizarse sistemas que aprenden y que
logran adquirir un conocimiento que no es directamente expresable en
nuestro lenguaje. Es decir que podemos construir máquinas que pueden
desarrollar conocimiento sobre la realidad, pero que no nos pueden
transmitir ese conocimiento. Es como la materialización del comentario
de los profesores mediocres, muy habituales en las aulas de
ingeniería, que no importa saber sino que importa tener el teléfono
del que sabe. En este caso, podemos construir "máquinas que saben" y
usarlas aún cuando no nos pueden explicar lo que saben.

* Realidad

Esto vendría a ser una especie de kernel o núcleo del sistema
operativo:

Parto de creer que la realidad existe y que no hay ningún genio
maligno tratando de engañarnos. Si bien la hipótesis de Matrix es
plausible, elijo no creerla. Entonces si la realidad existe la verdad
es una característica de las afirmaciones que podemos hacer sobre el
universo.

la verdad debería significar que lo que se afirma es tal como sucede
en la realidad. pero tenemos el problema de la complejidad y de la
multiplicidad de causas, y nuestra innegable limitación para
comprender. entonces tenemos que buscar sustitutos a una definición
que nos deja tan afuera. encontramos entonces esta cuestión de las
aproximaciones sucesivas, pero tiene el problema que hemos
descubierto, cada tanto nos damos cuenta de que la aproximación no
nos aproxima, como cuando la física clásica se vuelve relativista. el
cambio de paradigma es tan grande... otra definición más interesante
es la verdad como aquello que maximiza la coherencia de un conjunto
de ideas (un paradigma).

* Modelos

Se suelen utilizar modelos que representan la realidad, es decir que
nos indican el comportamiento de las variables que nos interesan, aún
cuando no haya una explicación convincente de la realidad que se
representa.

Puede haber caos allí donde hay reglas. La evolución de un sistema
depende de las condiciones iniciales y de las perturbaciones que
recibe (además de la estructura y función de sus partes).

* Conocimiento como caja negra

Distintos sistemas pueden dar los mismos resultados frente a las
mismas entradas, aún cuando sean estructuralmente distintos.

* Incertidumbre

Si se tiene una descripción de un sistema dentro de un rango aceptable
de incertidumbre, entonces es admisible trabajar a partir de esa
descripción a pesar de que carezca de un ajuste perfecto

* Pragmatismo - ingeniería

lo que puedo plantear es que el pragmatismo es la medida de la
verdad, pero que éste (el pragm) tiene sus límites, nos va a impedir
conocer ciertas cosas.

La condición de verdad que reina en el dominio de la ingeniería es el
pragmatismo. En tanto un instrumento o un proceso ofrece los
resultados deseados entonces resulta aceptable. En general los
desarrollos tecnológicos están orientados a resolver necesidades
humanas, así que el desarrollo de todo lo que cumpla con la función
para lo que fue pensado resulta aceptable. No hay aquí requerimientos
de ajuste a una realidad verdadera y cognoscible, sino la necesidad de
cumplir con ciertos fines.

* Necesidad de la verdad

Tener una mejor comprensión del mundo, contar con mayores
conocimientos de física, química, biología y demás ciencias puras,
permite teorías que puedan describir mejor la dinámica de un proceso,
predecir mejor el comportamiento.

la verdad tiene capas, como una cebolla. las capas externas de la
teoría atómica permiten explicar el funcionamiento de las bombas de
cobalto, aún cuando se utilicen modelos completamente superados y
notoriamente falsos. la analogía tiene el problema de que uno puede
tender a considerar que a capas más profundas hay mayor contenido de
verdad, cuando en realidad distintas teorías en distintas capas
pueden articular una visión del mundo mejor que una sola capa interna.

* Copernicanismo

Galileo fue el impulsor del modelo Copernicano en contra del sistema
geocéntrico aceptado hasta ese momento, propuesto por Ptolomeo y
Aristóteles, y sostenido por la Iglesia. En síntesis, el modelo de
Ptolomeo y Aristóteles de que la Tierra se encuentra fija, con los
astros (incluido el sol) girando en órbitas perfectamente circulares
alrededor de ella, fue el modelo sostenido mayoritariamente en
Occidente entre el siglo IV ac y el siglo XVI.

* Sobre los científicos

Todas estas cuestiones suelen estar ausentes de la conciencia que
tienen los científicos de sus prácticas, así que cuando opinan de los
métodos de la ciencia, de la fortaleza de sus argumentos, suelen
expresar una visión bastante simplificada de la actividad científica,
aunque sí son capaces de advertir, porque lo experimentan
permanentemente, los mecanismos políticos y económicos que atraviesan
la actividad que llevan adelante.

En general los científicos de la actualidad carecen de formación en
filosofía y en historia de la ciencia, puesto que toda la energía se
proyecta sobre la especialización en la disciplina desde la cual
deberán pelear por becas y subsidios. No creo que actualmente se
valore significativamente el disponer de herramientas ajenas a la
especialidad, ya que no se advierte que la epistemología, la
filosofía, la historia puedan aportar algo a la producción
científica. Habría que contrastar esto con la realidad de los físicos
de la primera mitad del siglo XX.

Las preocupaciones científicas de los investigadores
son de otra índole (en general están preocupados por sus resultados
experimentales y en cómo conseguir fondos para continuar).

La mayoría de los ingenieros y científicos "cree" en la inducción.

Los científicos (y los ingenieros) no saben nada de los problemas de
la epistemología.

Los argumentos como soldados. Se niega todo lo que no esté de acuerdo
con la linea principal.

Les preocupa el problema de la objetividad.

* El fenómeno de excitación-contracción

Hay en este problema una gran complejidad. Hay desplazamiento de
pequeños átomos cargados, llamados iones, a través de la membrana
celular y también a través de las membranas de los órganos internos
dentro de la célula, hay proteinas llamadas "canales" que dejan pasar
unos iones en particular y no otros (canales de sodio, canales de
calcio, etc), pero que afectan su funcionamiento frente a cambiantes
concentraciones de una tercer sustancia (moléculas que bloquean o
favorecen este funcionamiento), también hay otras proteinas que
funcionan como bombas (de sodio-potasio), a lo que se suma que la
estructura donde están fijadas estas proteinas tiene una consistencia
fluida, donde hay un movimiento constante de sus componentes, que a su
vez son muy dependientes de las formas para cumplir su función (un
canal es selectivo por las dimensiones que tiene su estructura, que
permite alojar un ion de sodio pero no uno de calcio). Además la
expresión de la información genética cumple un importante papel, y es
algo sobre lo cual los científicos pueden operar, puesto que
actualmente se diseñan animales de laboratorio con ciertas mutaciones
(por ejemplo la ausencia de una bomba).

Además, influyen sobre el sistema en estudio, el medio ambiente donde
se realizan las medidas, los resultados cambian cuando el tejido está
a distinta temperatura, en presencia de líquidos con distintas
concentraciones, etc.

También hay variaciones importantes en el funcionamiento del sistema
cuando se estudian las células por separado, ya que los resultados de
medir las mismas variables son distintos a cuando las mediciones se
realizan sin disgregar las células, es decir mientras estas aún están
formando parte de un órgano funcional.

La complejidad del sistema se profundiza con el agregado de
tecnologías para obtener información de los procesos que se tratan de
dilucidar. Para indagar se utilizan instrumentos y técnicas que pueden
alterar el funcionamiento de aquello que se estudia. Se utilizan
elementos para medir corrientes, temperaturas, presiones,
concentraciones, etc. Se sintetizan soluciones, se inyectan fármacos,
se realizan preparados para mantener con vida órganos aislados...

* Ingeniería. Desarrollo de tecnologías

¿es de carácter científico? (ciencias del diseño).
¿qué hago cuando me enfrento a un problema?
- multicausalidad
- complejidad

verdad es aquello que sirve y que puedo utilizar con cierto grado de
confianza en un razonamiento.

- simulaciones
- la existencia de conocimiento no verbalizable (el perceptrón)

el imaginario sobre el quehacer del ingeniero. ¿Es realmente
matemática lo que se usa?

Buena ciencia-ingeniería vs Mala ciencia-ingeniería

* Problemas de la simplificaciones. Cuerpos = máquinas.

La gente tiende a creer que los seres humanos somos máquinas que
funcionamos en un solo sentido. Creen que lo que pensamos, sentimos,
vemos, es el resultado de la expresión de la información genética y el
sinnúmero de fenómenos químicos que ocurren en nuestras células. No
faltan los papers que hablan del descubrimiento de la hormona que
genera la esperanza, el gen que causa la infidelidad, o la molécula
que causa la depresión. Pero este modelo no toma en cuenta que el
cuerpo puede ser un sistema bidireccional: nuestran sensaciones pueden
de algún modo actuar sobre nuestra química. Quizás esto tiene que ver
con el modelo de causa-efecto y con la reticencia a complejizar,
porque ya sabemos que existen montones de sistemas retroalimentados,
incluso en nuestro propio cuerpo.

* Ciencia en esencia

lo que es científico es la forma de conocer, la exahustividad de la
búsqueda. no es el método, ni que se trate de algo matemático o no.

Me gustó la definición de que verdad es la predisposición a la
búsqueda de quien investiga, y no es una propiedad en sí de la
teoría.

Lo científico es la predisposición a la investigación, a la búsqueda
de verdades, el inconformismo con el nivel de conocimiento actual, la
apertura a la discusión, ...

* Holismo vs especialización

La comprensión parcializada de la realidad por parte de los
científicos. La búsqueda de un lenguaje común derivó en lo que hoy es
la microespecialización. ¿Pueden entenderse realmente dos científicos
de la misma disciplina que estudian fenómenos diversos? Cómo esta
especialización atenta contra la comprensión holística de la realidad.

el recorte de las disciplinas es artificial, eso se nota en la
formación de los científicos de areas que incluyen campos diversos,
como la biofísica. En estos campos es que se vuelve notoria la
necesidad de una visión más holística, ya que los fenómenos no pueden
comprenderse utilizando los conceptos de una sola disciplina.

* Desconfiar de las observaciones

Cuando Franco hablaba sobre el modo "respetable" de producir
discursos (actos de habla de un cierto tipo, como en la producción
periodística de Rodolfo Walsh) remarcaba la necesidad de sostener ese
discurso en datos "objetivos de la realidad": documentos,
testimonios, estadísticas, etc. A primera vista podría parecer
parecer obvio que basta con esto. Pero podemos plantear algunas
preguntas: son todos los testimonios honestos, cómo se valoran los
datos que son contradictorios (porque la realidad no siempre se
expresa de manera coherente). Por ejemplo: los economistas, que usan y
analizan variables matemáticas y utilizan modelos computacionales,
pueden sacar conclusiones opuestas de sus estudios. Hay evidentemente
datos que es preciso desechar, como ciertas afirmaciones
gubernamentales sobre tal o cual cosa, o ciertas operaciones
periodísticas que presentan un velo demasiado endeble respecto de lo
que pretenden (no la verdad, sino otra cosa). No parece saludable
aceptar todo esto basado en la complejidad de los sistemas, porque hay
mentiras que se revelan ante el análisis. Pero hay que tener cuidado
de afirmar que siempre la realidad es cognoscible, registrable,
medible. Hay muchas interpretaciones que son necesariamente erroneas a
la luz de una inspección metódica, pero hay otras que son más
difíciles de desechar, porque aparecen ahí indicios contradictorios,
información que no es concluyente (como en el ejemplo de los
experimentos para mostrar que la tierra gira tirando una piedra desde
una torre).

Cita de Einstein, Fey. Pg 41 (nota al pie) "Es realmente extraño que
los hombres sean, por lo general, insensibles a los más fuertes
argumentos mientras que siempre están inclinados a sobrevalorar la
exactitud de las mediciones." (podría buscar cosas sobre la oposición
entre físicos teóricos y físicos experimentales)

* Beneficios del avance tecnológico

Respecto de los beneficios de la ciencia, el hecho de tener
celulares, medicamentos, etc.

cómo se distribuye el dinero en ciencias? qué campos reciben más, qué
lineas de investigación se apoyan más?

* La insuficiencia de la verdad para la acción

El problema de la falta de compromiso de los lectores y el hecho de
que no se desencadenen escándalos con consecuencias reales es también
un problema para la ciencia, si pensamos que la ciencia no debe ser
dominio exclusivo de los científicos sino de un público (ilustrado)
general. ¿Qué nos toca hacer frente a esto? Yo creo que hay que
criticar sin piedad al sistema científico, sin endiosarlo por sus
logros, y mostrar que el público general puede participar de sus
procesos, que no incluyen sólo la producción del conocimiento sino su
difusión, la participación en la selección de problemas relevantes,
la auditoría de las instituciones, etc. Por eso es importante una
educación que permita a las personas participar adecuadamente en
estas tareas.

* La autocrítica en ciencias. El contacto con otras tradiciones.

Algo que me parece imprescindible para el espíritu científico es
advertir las debilidades de las propuestas que uno hace, de las
teorías que uno tiene. Recibir la crítica y evaluarla y no empezar
por ridiculizarla, sino por tratar de entender desde la óptica del
otro. Muchas veces esto puede conducir igual a reafirmar lo que uno
piensa, pero quizás no siempre. Se puede aprender de puntos de vista
no expertos o no especializados (por ejemplo en quienes pueden
elaborar sistemas de comprensión basados en el uso de
analogías). Todas las tradiciones pueden aprender de otras, unas
disciplinas pueden aprender de otras, de otras culturas y formas de
pensamiento. La realidad es tan rica que quizás tiene aspectos que no
son binarios, en los que podrían ser aplicables lógicas diversas. O
hay que advertir que el binarismo es posible siempre que permita
cierta flexibilidad (¿qué onda con los sexos, no es acaso absurdo
plantear la pregunta sobre si una persona es mujer o varón?).

De Feyerabend: pg4. En respuesta a si es deseable apoyar la ciencia
como único camino para comprender el mundo, responde que no y que hay
dos razones para ello: "La primera consiste en que el mundo que
deseamos explorar es una entidad en gran medida desconocida. Debemos
por tanto mantener abiertas nuestras opciones y no restringirlas de
antemano. ... ¿Quién garantiza que [las prescripciones
epistemológicas] constituyan el mejor camino para descubrir, no ya
unos cuantos "hechos" aislados, sino ciertos secretos profundos de la
naturaleza? La segunda es que una educación científica como la
descripta antes (y como se imparte en nuestras escuelas) no puede
reconciliarse con una actitud humanista".

* Lenguaje

Es necesaria una riqueza del lenguaje para poder comprender el mundo.

Después está el problema de usar un lenguaje suficientemente bueno
para describir un proceso. Se puede caer en el error de evaluar el
sistema educativo basando el juicio en ciertos valores estadísticos,
cuando los mismos no representan la realidad de lo que pasa dentro de
un aula.

* Ciencia vs No-Ciencia. O ciencia en el capitalismo

A veces la discusión es entre ciencia vs no-ciencias, cuando la
dicotomía más peligrosa es buena ciencia vs mala ciencia.

Pensemos en el sistema científico y en cómo su producción no
solamente sirve para brindarnos celulares y vehículos a precio
accesible, sino una batería de muletas para el modo de producción
capitalista.

* Feyerabend

Feyerabend plantea que los niños no aprenden sólo por la
argumentación durante la enseñanza, sino a "un proceso de crecimiento
que se desarrolla con la fuerza de una ley natural. Y donde los
argumentos parecen tener efecto, éste se debe más a menudo a su
repetición física que a su contenido semántico. Después de admitir
todo esto, hemos de aceptar también la posibilidad de crecimiento
no-argumentativo en el adulto... debería esperarse que los cambios
catastróficos del contorno físico, las guerras, el colapso de los
sistemas de moralidad imperante, o las revoluciones políticas, habrán
de transformar también los modelos de reacción del adulto, incluidos
importantes modelos de argumentación. Esta transformación puede ser
también un proceso completamente natural, y la única función de la
argumentación racional quizás radique en aumentar la tensión mental
que precede y **causa** la explosión de la conducta.

Ahora bien, si son los eventos, no necesariamente los argumentos, la
causa de que adoptemos nuevos criterios, incluyendo formas nuevas y más
complejas de argumentación ¿no es cierto que los defensores del statu
quo tendrán que aducir no sólo contra-argumentos, sino causas
contrarias? ("la virtud sin el terror es ineficaz", dice Robespierre).
Y si las viejas formas de argumentación resultan demasiado débiles
para constituir una causa, ¿no deberán estos defensores o bien
abandonar, o bien recurrir a medios más fuertes y más irracionales?
(Es muy dificil(Pg 8-9).

* Enseñanza a-histórica

Tenemos la sensación, al estudiar ciencias, por el modo en que se
presentan los conocimientos, de que las distintas disciplinas
tuvieron un progreso continuo y sus teorías conforman un cuerpo
explicativo coherente, sin fisuras. Nunca se mencionan las
observaciones que cuestionan las teorías, ni cómo se dieron los
conflictos cuando teorías opuestas se encontraban en disputa.

* Feyerabend sobre la sustitución de teorías

Sobre la sustitución de teorías: El progreso se consigue a menudo por
medio de una crítica desde el pasado... Después de Aristóteles y
Ptolomeo, la idea de que la Tierra se mueve -esa extraña, antigua, y
"completamente ridícula" concepción pitagórica- fue arrojada al
montón de escombros de la historia, para ser revivida sólo por
Copérnico y para convertirse en sus manosen un arma con la que vencer
a los vencedores de dicha concepción. (Pg 33) En esto quizás puedo
plantear una analogía entre el "viejo" Lisp y los modernos lenguajes
de computación (o por ejemplo las modas de la programación orientada
a objetos y la programación funcional). Sigue Feyerabend: "Semejantes
desarrollos no son sorprendentes. Una idea no se examina nunca en
todas sus ramificaciones y ningún punto de vista recibe jamás todas
las oportunidades que se merece. Las teorías se abandonan y
sustituyen por otras explicaciones más de moda, mucho antes de tener
la oportunidad para mostrar sus virtudes.

* Pendiente

La idea de que el conocimiento para vivir mejor ya está..

pensar sobre las dos teorías sobre el registro del ecg. cuál es
veradadera?

programa de magia: "recursos atencionales" ¿realmente este concepto
sirve para explicar algo? es como el poder somnífero o el poder
curativo de una sustancia. / Redes. Magia y neurociencia en red.
