#+TITLE: La única verdad es la incertidumbre
#+DESCRIPTION: Apuntes personales acerca del conocimiento en las ciencias
#+AUTHOR: Diego Fainstein
#+DATE:
#+OPTIONS: toc:nil

#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LANGUAGE: es
#+LATEX_HEADER: \usepackage[spanish]{babel}

* Aclaración

Me parece importante aclarar que mis opiniones, reflexiones y puntos
de vista están construidos desde lo que sería una "visión del
usuario", a partir de mis experiencias laborales y mis lecturas. Esto
es diferente a una exposición hecha por un experto, que en este caso
sería un epistemólogo. No voy a citar a Habermas, ni a Marcuse, ni a
Hegel, exclusivamente porque no los he leído. Sin embargo, yo creo que
la palabra de los expertos no es la única que puede contribuir a la
construcción del conocimiento, así que los invito a escucharme y a
dialogar o debatir.

De todos modos, siempre es posible que algunas de mis observaciones
puedan ser consideradas superficiales, superadas o directamente
erroneas. En ese caso, espero que estén atentos y lo señalen, tanto
durante la exposición como al final.

También quiero advertir que mi expectativa no es convencer sobre la
validez de mis afirmaciones, sino cuestionar algunas perspectivas
demasiado idealizadas acerca de las ciencias, que se dan justamente en
los ámbitos en que he trabajado. Mis reflexiones surgen en respuesta a
un modo dominante de hacer ciencia, diseñar tecnología y enseñar. Mi
propósito con esta presentación es incomodar esas concepciones para
que nadie esté cómodo ni afirmando que el conocimiento científico del
modo en que lo conocemos es despreciable ni encumbrándolo como a un
ídolo único e indiscutible.

Esto me preocupa un poco porque en el mundo se extienden y fortalecen
distintas formas de fundamentalismo e irracionalidad, con lo cual
parecería que es irresponsable cuestionar a aquello que se identifica
con la razón y la libertad. Sin embargo acallar la crítica agitando
"el fantasma de la derecha" nos convertiría justamente en aquello que
rechazamos.

* Mis ámbitos de trabajo.

Voy a presentar algunas ideas en relación con mis espacios de
trabajo, actuales y pasados, por lo que me parece importante para
situar a todos en el contexto en el que se desarrollan estas
reflexiones, describir brevemente estos lugares y sus características
sobresalientes, los cuales constituyen entornos donde el concepto de
verdad cobra distintos significados o tiene diferentes alcances y
particularidades.

** Enseñanza

Empecé como auxiliar-alumno en 1998, en la carrera de
Bioingeniería. Actualmente soy Jefe de Trabajos Prácticos en dos
asignaturas: Bioingeniería II y Medicina Nuclear (de acuerdo a la
nomenclatura del Plan 1993). La primera aborda las técnicas para
obtener y procesar información del mundo real y en particular del
cuerpo humano (se estudian los modos de medir la temperatura, la
presión arterial, la actividad eléctrica del corazón en la forma del
electrocardiograma, etc) mientras que la segunda se ocupa de los usos
de las radiaciones ionizantes para diagnóstico (es decir para la
obtención de imágenes del cuerpo humano) y para tratamiento
(principalmente del cancer).

** Investigación y Desarrollo

Participé en tareas de investigación en el campo de la
electrofisiología cardíaca, tanto en la Facultad de Ingeniería como en
visitas temporarias a un laboratorio de esta especialidad en Estados
Unidos.

Trabajé dentro de grupos que se ocupan de dos grandes temas:

  1. Uno es la variabilidad de la frecuencia cardíaca: a partir del
     registro del electrocardiograma mediante electrodos superficiales
     se calcula la frecuencia cardíaca, que va variando latido a
     latido, y se trata de correlacionar esa información con diversos
     estados fisiológicos y fisiopatológicos (como el estrés), para
     obtener un índicador clínico de la condición de salud o
     enfermedad del paciente.

  2. El otro tema es el fenómeno de excitación-contracción: se trata
     de indagar en los mecanismos celulares involucrados desde que
     llegan los impulsos nerviosos a las células cardíacas, hasta que
     éstas se contraen, y logran en conjunto y coordinadamente que el
     corazón realice su función de bomba.

*** División del campo

Voy a presentar algunas ideas sobre la verdad diferenciando entre
especificidades en estos tres campos: ciencias, tecnologías y
enseñanza.

Quería aclarar que la división es arbitraria y tiene más que ver con
tratar de presentar las ideas en forma ordenada y secuencial que en
hacer una diferenciación analítica seria. Las tareas de investigación
"pura" y de desarrollo de tecnología están relacionadas y se necesitan
mutuamente.

En general las ideas más difundidas y discutidas de las diferentes
escuelas epistemológicas, desde el positivismo en adelante, se
refieren a las ciencias puras, es decir aquellas que se ocupan de
descubrir cómo es el universo, cómo funciona la naturaleza, y
demás. Para ellas se plantean y se discuten, por ejemplo, diferentes
modelos metodológicos.

El desarrollo de tecnologías o las ciencias aplicadas (que son los
viejos oficios pero profesionalizados, y que podemos llamar "ciencias
del diseño") tienen particularidades, ya que su objetivo no es tanto
comprender el mundo sino operar sobre él, mediante la creación o
modificación de procesos o instrumentos para cambiar nuestro entorno.

Debe tenerse en cuenta que esta diferenciación se vuelve difusa dado
que las ciencias básicas requieren de tecnologías más sofisticadas
para permitir la realización de experimentos, mientras que el
descubrimiento de las leyes naturales habilita al avance de las
ciencias del diseño.

En ambos casos mi participación principal tuvo más que ver con la
construcción de instrumentos de medición para obtener información en
cada uno de estos dos campos. No trabajé directamente en la
elaboración de teorías y experimentos, sino en posibilitar estos
últimos, pero en ambos estuve en contacto con investigadores "básicos"
y sus discusiones acerca de las incógnitas del campo de estudio, las
teorías que pretendían probar o cuestionar y los experimentos para
materializar estos propósitos.

* Ciencia y realidad

En los ámbitos que conozco las personas son realistas duras, que
asumen la existencia de una realidad objetiva, independiente de los
seres humanos, de nuestros deseos, de nuestros sentidos. La mayoría,
sino todos, creen que la realidad es tal cual la registramos con
nuestros equipos. Los instrumentos nos muestran lineas que se dibujan
en el monitor o números en el panel frontal de un amplificador, y a
través de ellos vemos (o quizás imaginamos) proteinas cambiando de
forma, iones que se desplazan a través de una membrana, impulsos
nerviosos que chocan con células muertas. Entrenados en la
interpretación de estas observaciones, se desarrolla una familiaridad
con las teorías que permite ir comprendiendo los fenómenos con una
profundidad cada vez mayor. En lo que Kuhn llamaría un período de
ciencia normal vamos desarrollando progresivamente el conocimiento
mediante teorías y experimentos cada vez más explicativos. No advierto
instrumentalismo: lo que registramos es lo que existe en realidad, hay
correspondencia entre nuestras afirmaciones y la estructura de lo que
investigamos.

Los experimentos se diseñan para obtener información útil sobre un
proceso. Para ello se establecen condiciones de manera que la
variación controlada de un solo parámetro sea el que provoca los
cambios que se pueden registrar con los instrumentos de medición. Por
ejemplo, se registra la diferencia de potencial entre el interior y el
exterior de una célula, manteniéndola inmersa en una solución que la
mantiene con vida, pero siempre con el mismo pH, las mismas
concentraciones de glucosa, bicarbonato, etc. De este modo se puede
investigar, por ejemplo, cómo responde el potencial a cambios en la
temperatura, sabiendo que los cambios no pueden deberse a variaciones
en el contenido de la solución fisiológica. La información obtenida se
analiza en busca de relaciones entre la variable testeada y distintos
parámetros del registro, con el propósito de encontrar correlaciones y
causalidades. También se realizan experimentos para ver el mismo
fenómeno con diferentes técnicas, lo cual puede ofrecer información
nueva. Si el planteo de un experimento fuera caótico, o si estuviese
diseñado inadecuadamente, los resultados no permitirían concluir nada.

De acuerdo a lo que se investiga, la realidad puede describirse con
esquemas, ecuaciones, modelos, analogías, fotografías, registros
temporales de la evolución de distintas variables, reglas, tablas de
probabilidades, etc.

Si un fenómeno ocurre tiene una o varias causas y distintos efectos, y
no tiene mucho sentido realizar suposiciones que resulten irracionales
a la luz de nuestros saberes actuales. Esto es así porque se pretende
cierta eficiencia en el proceso de develar lo desconocido. Hay un
marco teórico a la luz del cual se interpretan los resultados. Si hay
que describir cómo se limita la cantidad de iones de calcio que
ingresan a la célula cardíaca cuando llega un impulso nervioso, una
explicación relacionada con las fuerzas sutiles del lado oscuro o con
la memoria cuántica de la flecha del tiempo sería impublicable, salvo
en revistas literarias, o en revistas de dudosa calidad científica. Se
supone también que la naturaleza funciona con regularidad, es decir
que --por ejemplo-- un canal de calcio tiene siempre la misma cinética
en condiciones semejantes y hay ciertas limitaciones en cuanto a las
variables a las cuales podemos atribuir participación en el fenómeno,
de acuerdo al conocimiento actual.

No hay en este esquema de trabajo lugar para afirmaciones relativistas
extremas, tales como que es válida cualquier interpretación laxa de
los resultados obtenidos. Primero por la suposición realista de que la
naturaleza funciona de alguna forma coherente y regular (incluyendo
los fenómenos probabilísticos y caóticos que también presentan rasgos
de coherencia y regularidad), y segundo por la evaluación a la que es
sometida la investigación y de la cual depende su aceptación y
posibilidad de continuidad. Si bien los científicos aceptan que las
teorías tienen diverso grado de aproximación a la realidad, que lo
establecido está sometido a cambios, y se entiende que los modelos
descriptivos o explicativos pueden mejorarse, no se advierten estas
salvedades en las conversaciones cotidianas.

Los jueces de esta verdad son los pares, principalmente los revisores
de los artículos que aparecen en las revistas especializadas y también
los evaluadores en las instituciones que otorgan el presupuesto para
continuar las investigaciones. Frecuentemente cuando un artículo es
rechazado o cuando se pierde un subsidio se duda sobre la
imparcialidad o la pericia de los evaluadores antes que de la
debilidad de los propios argumentos. No voy a desarrollar estos
aspectos sociológicos de la investigación científica, aunque me
resultan muy interesantes y explicativos de la actividad.

** Problemas reales

La adecuación a ciertas normas metodológicas y de razonamiento
intentan depurar el conocimiento de charlatanería e imprecisiones, de
manera tal que se puedan establecer conocimientos sólidos para el
avance en la comprensión de las distintas disciplinas, y así
traducirse finalmente en una mejor comprensión del universo.

Pero vamos a plantear algunas dificultades. En primer lugar da la
impresión de que no hay mucho lugar para las contradicciones, o que
éstas son facilmente eliminables en base a la experimentación y a la
contrastación intersubjetiva por parte de la comunidad de pares.

Sin embargo los resultados experimentales no siempre son fáciles de
analizar. A veces la información dice una cosa en un conjunto de
experimentos y otra muy distinta al analizar iguales experimentos
realizados en las mismas condiciones, y no se sabe de dónde proviene
la divergencia. ¿Hubo algún error en la concentración de una solución?
¿Hubo problemas con el instrumental de registro?  ¿Estuvo la persona
encargada del experimento realmente atenta y anotó todo lo ocurrido?
¿El tejido donde se realizó el registro se preparó sin causarle daños?
Muchas cosas pueden salir mal y suele destinarse mucho tiempo a
depurar los experimentos, ajustar los instrumentos para que su
funcionamiento sea sólido, consistente, inmune a las perturbaciones.

Cuando se obtienen resultados dispares, al utilizar las mismas
herramientas o al usar diferentes metodologías para analizar el mismo
proceso, el motivo de la disparidad puede estar en que efectivamente
se estén produciendo errores sistemáticos (que se podrán solucionar
respondiendo a preguntas como las que formulé recién) o puede ser
que la evidencia sea efectivamente caótica porque el sistema que se
analiza tiene una complejidad tal que pequeñas variaciones en un
parámetro producen grandes efectos, o quizás la presencia de una
variable desconocida tiene una influencia que no podemos advertir, o
incluso puede ser que la teoría que subyace a nuestras observaciones
no nos permite valorar adecuadamente lo que observamos. Tengamos en
cuenta que lo que observamos a través de nuestras sensaciones e
instrumentos está sometido a la interpretación que hacemos de los
datos, para lo cual siempre estamos utilizando teorías, nos demos
cuenta de esto o no. Y estos no son los únicos problemas que pueden
aparecer.

*** Ejemplo: geo y heliocentrismo.

Para ilustrar esto voy a comentar brevemente uno de los ejemplos más
paradigmáticos respecto de la oposición entre ciencia y religión. Desde
el siglo IV(ac) hasta el siglo XVI se mantuvo mayoritariamente aceptado el
modelo geocéntrico propuesto por Ptolomeo y Aristóteles, el cual
contaba con la bendición de la Iglesia Católica y su eficaz máquina
propagandística, incluyendo la técnica publicitaria conocida como
Inquisición (ja). Durante el Renacimiento, Galileo construye varios de
los primeros telescopios (aunque no es su inventor) y realiza
observaciones (como por ejemplo de las lunas de Jupiter) que permiten
cuestionar el modelo geocéntrico. A pesar de que conocemos el
desenlace, y sabemos que la teoría geocéntrica es incorrecta, voy a
utilizar el ejemplo para mostrar que las observaciones de Galileo y de
sus oponentes no eran necesariamente evidentes, obvias y fáciles de
aceptar. Con esto pretendo mostrar cómo el relato simplificado de los
hechos que lleva a colocar en el lugar del absurdo las posiciones
geocéntricas le otorgan al empirismo una fortaleza inmerecida.

Hay al menos dos aspectos del problema que me gustaría plantear:

*Punto 1* Los conocimientos de óptica de Galileo no eran suficientes
para que resultaran incuestionables las observaciones hechas con el
telescopio. Una cosa es que se pudiera comprobar que con este nuevo
instrumento se podía ampliar una imagen conocida dentro de la Tierra,
y otra es que pudiese funcionar de manera confiable para observar
objetos celestes. Por ejemplo: ¿era posible entender qué significaban
las distorsiones de los sistemas primitivos de lentes o sospechar el
efecto de la refracción en la atmósfera terrestre? ¿Acaso pensamos que
los telescopios de Galileo ofrecían una calidad de imagen comparable a
los disponibles en la Asociación Entrerriana de Astronomía?  Gran
parte de la física óptica necesaria para comprender el telescopio no
estaba al alcance de Galileo y fue desarrollada después. Además las
observaciones eran inconexas también con las predicciones de la teoría
copernicana, por ejemplo el hecho de que las dimensiones de los
planetas a lo largo de su órbita no coincidían con las diferencias que
anticipaba esta teoría.

Para plantear una analogía podríamos sustituir el instrumento
"telescopio" por el instrumento "Wikipedia". Si no supiésemos cómo
funciona quizás empezamos a usarla para buscar ciertas definiciones y
vemos que los resultados que nos ofrece coinciden con información que
ya conocíamos o que previamente buscamos en otra
enciclopedia. ¿Alcanza con eso para confiar en que toda la información
que en adelante busquemos en Wikipedia será veraz?  Por supuesto que
no, y esto no quiere decir que la información de la Wikipedia no sirva
para nada. Podemos resumir todo esto afirmando que la observación no
es independiente de la teoría, que lo que observamos está condicionado
por lo que sabemos. Otro ejemplo: imágenes obtenidas del cuerpo humano
mediante rayos X, tomografía computada, resonancia magnética,
tomografía de emisión de positrones y demás, nos brindan información
que no todos estamos en condiciones de interpretar y además, aquellos
que sí lo están, no siempre pueden efectuar lecturas carentes de
errores a partir de ellas o lecturas coincidentes entre sí. Siempre
hay una interrelación entre observación y teoría, lo cual vuelve
dificil aceptar que haya posibilidad de efectuar observaciones puras
que puedan fortalecer o debilitar puntos de vista en conflicto. En el
lenguaje de la epistemología se suele decir que las observaciones
están imbuidas de teoría.

*Punto 2* En segundo lugar, volviendo al ejemplo de Galileo, se
puede afirmar que había elementos empíricos también en el campo de los
aristotélicos. Por ejemplo: para sostener que la Tierra no se movía
planteaban el siguiente experimento. Si se deja caer una piedra desde
una torre muy alta y la Tierra se mueve, sería razonable que la piedra
no cayese sobre la base de la torre, sino a una distancia igual a la
distancia recorrida por la Tierra durante el tiempo en que se produjo
la caida. Otro argumento en el mismo sentido: si dos proyectiles se
lanzan en direcciones opuestas con la misma fuerza, deberían recorrer
distinta distancia. Faltaba la noción de inercia, para explicar estos
dos hechos contradictorios con la tesis heliocéntrica. Lo que muestran
estos ejemplos es que la obviedad de una hipótesis recién se logra
mucho tiempo después de que teorías rivales disputan cuál es aquella
con mayor contenido de verdad.  Con esto podemos apreciar que cuando
el conocimiento trata de expandirse sobre terreno desconocido se
enfrenta con desafíos que no son tan triviales como lo proponen
positivistas y falsacionistas. Quizás estas reflexiones nos permitan
esquivar el peligro de convertirnos en dogmáticos defensores del
empirismo.

Para un estudio detallado de cómo se dio la conversión del
geocentrismo al heliocentrismo se puede leer "Tratado contra el
método" de Paul Feyerabend.

En conclusión, la contrastación empírica parece cobrar más fuerza
cuando ya se ha desarrollado la teoría, y cuando no se trata solamente
de un solo tipo de observación sino que ya existe un entramado de
argumentos que fortalecen un modelo explicativo por sobre otro.

** Sistemas complejos: especialización y holismo.

*** Introducción

La ciencia logra una comprensión relativamente profunda de algunos
aspectos de la realidad. En algunos casos nos resulta evidente la
correspondencia entre las consecuencias que podemos experimentar
respecto de una teoría y la propia realidad. ¿Es aceptable cuestionar
la ciencia teniendo en cuenta sus logros? ¿Nos convierte eso en
apóstatas que en aras de la coherencia deberían renunciar a los
tratamientos médicos modernos y al uso del whatsapp? Para mi no se
trata de rechazar esta forma de conocer sino de advertir que hay
distintos niveles de verdad en el conocimiento científico. Cuando se
trabaja sobre un sistema complejo, se pueden hacer afirmaciones
verdaderas, pero cuyo alcance descriptivo o explicativo tiene límites.

*** La complejidad del fenómeno de excitación-contracción

Para estudiar el fenómeno de excitación-contracción hay muy diversas
técnicas y aproximaciones. Se pueden realizar mediciones eléctricas u
ópticas, con preparados de células aisladas o sobre porciones de
tejido o incluso en corazones enteros, sobre diversos modelos
animales: ratón, conejo, rata, cerdo, etc. Algunos métodos se utilizan
mucho porque son relativamente económicos o fáciles de implementar, o
porque el éxito de alguna investigación les dio impulso y se
popularizaron. Pero justamente ocurre lo siguiente: los resultados
obtenidos son contradictorios. Lo que sucede en la célula aislada es
diferente a lo que sucede en el corazón completo, y por lo tanto, lo
que se descubre sobre los mecanismos en un nivel de organización
celular no es tan fácil de extrapolar para comprender lo que sucede en
el órgano completo. No quiere decir que lo que averiguamos tras
fraccionar el sistema es inútil, sino que es limitado lo que podemos
saber si sólo hacemos estudios analíticos.

*** La medicina y la materialidad ingenua

Esto que sucede a nivel celular y tisular se amplifica cuando tratamos
de comprender los macrosistemas. Al considerar el cuerpo completo de
una persona es indeterminada la cantidad de variables
interrelacionadas que tienen efecto sobre la porción del cuerpo que
pretendemos investigar. Es necesario un estudio de las partes, pero el
funcionamiento de la totalidad no es solamente la suma del
funcionamiento de las fracciones. En el sistema completo (algo
también aplicable a los sistemas sociales) se dan interacciones
múltiples y complejas que modulan el comportamiento de los componentes
individuales.

Pensemos el caso del cuerpo humano, el cual en la medicina científica
tradicional tiende a explicarse desde una perspectiva
mecanicista. Tras una corta búsqueda en PubMed se pueden encontrar
títulos como estos: /Asociación entre los genes del receptor de
dopamina con la infidelidad y la promiscuidad sexual/, /Correlaciones
neurales del perdón a las transgresiones morales que implican engaño/
(estudios realizados con PET), /La genética de las adicciones/,
etc. Indudablemente hay correlaciones entre la base física y nuestras
emociones y comportamientos, pero hay acá un detalle sobre el que
quisiera ahondar.

El descubrimiento en el mundo occidental, por parte de William Harvey
en el siglo XVII, de que la sangre es impulsada a través de arterias y
venas por el corazón (que funciona como una bomba hidráulica) recién
se logró cuando se desarrollaron los conceptos físicos que permitían
concebir este esquema. Tomar un modelo de un sistema que comprendemos,
para explicar otro aún bajo investigación, puede abrirnos la
posibilidad de grandes descubrimientos. Sin embargo, si nos
entusiasman los excelentes resultados de esta estrategia y nos
quedamos prisioneros de una concepción mecanicista del Hombre,
podríamos llegar a creer que todo puede ser explicado en términos
materiales simples; es decir que el funcionamiento de nuestro cuerpo,
nuestro comportamiento, emociones y decisiones pretendería ser
explicado en función de enlaces químicos, información genética y masas
en movimiento. La vinculación es innegable, pero es insuficiente como
explicación, como instrumento de comprensión.

*** Materialistas analizan una computadora

Imaginemos esta situación: un grupo de materialistas ingenuos se
encuentran una computadora moderna que en su mundo no existe. ¿Van a
ser capaces de explicar el funcionamiento de la misma a través de
mediciones sobre sus componentes físicos? Tras una enorme cantidad de
experimentos muy sofisticados de expertos en la química del silicio,
en física eléctrica, en termodinámica y transferencia de calor, es
evidente que sabrán mucho de las distintas partes de la computadora,
pero desconocerán lo esencial de ella, la existencia de lo que
llamamos software, es decir el conjunto de instrucciones que organizan
el funcionamiento de la máquina. Este software carece prácticamente de
correlato en el mundo físico, y de hecho puede funcionar igual en
distintos soportes (distintos microprocesadores), así que es casi
imposible de ver aún cuando se examine el hardware con microscopios
electrónicos y osciloscopios. En otras palabras, la realidad puede ser
reconocida limitadamente de acuerdo a la utilización de un tipo de
prácticas de investigación. ¿Calificarían de pseudo-científicos a los
que planteasen que el comportamiento de la computadora tiene que ver
con un aparato psíquico inmedible o con un /espíritu/? ¿Será razonable
limitar las teorizaciones sobre el funcionamiento de la computadora a
lo que experimentable mediante la interacción con la pantalla y el
teclado (es decir mediante una forma de psicología del
comportamiento)? Lo que quiero mostrar es que hay criterios de
demarcación del conocimiento científico que reducen lo susceptible de
conocerse a aquello medible y de materialidad más ingenua. Concebir la
ciencia de esta manera puede llevarnos a rechazar modos de conocer la
realidad más sujetos a la especulación, y a calificar a aquello que
cae fuera de pura charlatanería.

*** Lenguaje

Un proyecto importante del positivismo fue el de desarrollar un
lenguaje único para la ciencia. Si bien las matemáticas se usan como
herramienta y pueden ser comprensibles para especialistas de diversos
campos, es absurdo pensar que un físico teórico habla el mismo idioma
que un biólogo molecular. Hoy en día, en congresos y encuentros,
da la sensación de que científicos que investigan incluso dentro de
una misma disciplina apenas pueden entenderse, debido al grado de
especialización y las particularidades de cada problema.

Lo más cercano al proyecto unificador podría ser la idea de conformar
equipos de investigación que integren a especialistas de diversas
disciplinas, así se vuelve posible que un mismo fenómeno se estudie
simultaneamente desde distintas perspectivas. Por ejemplo, en el
estudio del fenómeno de excitación-contracción se pueden encontrar
biólogos, bioquímicos, físicos, informáticos, médicos, ingenieros,
veterinarios, etc. Hay herramientas que son comunes y comprensibles
para todos, pero el lenguaje en común está en permanente construcción,
y los significados de ciertos experimentos, o técnicas o resultados
pueden ser difíciles de explicar y compartir.

Todo lenguaje usado para describir o explicar un fenómeno tiene
limitaciones. En informática se han desarrollado enorme cantidad de
lenguajes y dialectos con el propósito de dar mejor respuesta a
diferentes problemas. Por ejemplo para escribir programas de
inteligencia artificial suele usarse Lisp o Prolog u otros
semejantes. No cualquier lenguaje tiene la misma potencia para
resolver todos los problemas informáticos. Del mismo modo, podemos
pensar que la utilización de un lenguaje en particular, sea el
castellano, o el lenguaje de la química, o las matemáticas, limitan la
manera en como pensamos, describimos y explicamos la realidad.

La matemática incluso, como lenguaje aparentemente objetivo, no
garantiza la comprensión:

Por ejemplo, algunas instituciones relacionadas con la educación, como
la propia facultad de ingeniería, utilizan ciertos indicadores
matemáticos para dar cuenta de lo que entienden como /calidad de la
enseñanza/. Cuantifican la relación del número de docentes al número
de alumnos, la cantidad de alumnos aprobados y reprobados en cada
cuatrimestre, y el promedio de las notas. Creen que de esta manera
tienen información sobre el sistema educativo. Por supuesto que logran
construir a partir de estas observaciones una descripción, pero dudo
mucho de que puedan comprender realmente lo que sucede en las aulas.

Otro ejemplo de manipulación de la realidad con herramientas
matemáticas puede ser la descripción de la economía mediante la
selección arbitraria de parámetros.

*** La verdad como un entramado autocoherente.

Hay una imagen que se me presenta cuando imagino la forma de  nuestras
concepciones sobre el mundo: la de una tela de araña. Quizás en
algunos casos cuando los sistemas que estudiamos son menos complejos,
efectivamente podamos pensar que la verdad describe a la realidad tal
cual es. Pero en los sistemas más complejos e interesantes este ajuste
es dificultoso de lograr. Es más razonable pensar que las verdades que
podemos producir sólo tienen algunos puntos de contacto con la
realidad mientras que gran parte de nuestras afirmaciones sólo son
verdad en tanto mejoran la coherencia de nuestros modelos explicativos
(esto sería como una postura instrumentalista) sin que estén tan
ajustadas a la realidad. Verdades, entonces, serían aquellas
afirmaciones que tiendan a que el modelo explicativo sea cada vez más
autocoherente, como si estuviésemos construyendo una tela de araña
donde sus puntos de apoyo fuesen las comprobaciones empíricas y las
teorías fuesen hilos que deben fortalecer la estructura de la tela,
aún cuando no necesariamente brinden muestras inequívocas de estar
vinculadas con la realidad.

*** Conclusión

Pretendo señalar que la ciencia puede no abarcar al objeto de estudio
en su totalidad. Debemos ser concientes de las limitaciones que impone
la investigación científica basada en la especialización. No es
tampoco fácil pensar en un modo de producción de conocimientos más
holístico e interdisciplinario que no caiga en la improductividad o el
cualquierismo.  De todos modos está claro el peligro de negar todo
aquello que no se comprende. La investigación científica debería
mantener apertura y flexibilidad, aún cuando se corra el riesgo de
elaborar conocimientos y teorías espúreas.

Lo fundamental en ciencias no me parece que deban ser los métodos de
investigación y el empirismo, sino el apego a la crítica, la admisión
de una pluralidad de ideas en conflicto, y la evasión de toda forma de
dogmatismo. Esto quizás le quita certeza, nos sumerge en un mundo de
incertidumbres, pero le agrega potencia a nuestra capacidad de
conocer. Tener esto presente también nos habilita a reconocer el valor
de las disciplinas que no necesitan ser científicas para producir
conocimiento (la filosofía en general, la metafísica en particular, la
política, psicología, etc).

Por supuesto que toda esta propuesta choca contra el modo en que está
organizado el sistema científico y tecnológico, y los propósitos que
persigue.

* Tecnología, ciencias del diseño

La función más interesante de los ingenieros es actuar sobre la
realidad para dar respuesta a alguna necesidad humana (o del
mercado). Los bioingenieros con tareas más específicamente técnicas,
como los que se ocupan del mantenimiento de hospitales y clínicas, o
del diseño de instrumentos utilizados en el cuidado de la salud,
dependen de los conocimientos y teorías de las distintas
disciplinas. Es obvio que una mayor comprensión de los fenómenos
físicos y biológicos fortalece las posibilidades de tener éxito al
diseñar nuevos instrumentos, o al identificar fallas, o al controlar
procesos.

También hay tecnologías que producen conocimiento sobre el mundo
sin pretensión de realidad. Esta característica de volverse generadora
de conocimientos difumina el límite entre ciencia y tecnología, y
aleja la concepción de tecnología como una mera aplicación del
conocimiento científico. Mediante la tecnología se pueden construir
representaciones parciales de la realidad, es decir sistemas
artificiales que modelan un aspecto del mundo real, que nos brindan
información aún cuando la estructura y los fenómenos internos del
sistema real nos sigan siendo desconocidos. En otras palabras podemos
decir que a través de la tecnología se construye un conocimiento
instrumental del mundo.

Puedo dar un ejemplo con la intención de ilustrarlo:

Se puede elaborar un conjunto de ecuaciones diferenciales que
representan el funcionamiento del sistema cardiovascular y gracias a
ellas saber cómo será la distribución de la presión en el corazón y en
las arterias y venas, o cómo variará el volumen de las cavidades del
corazón a lo largo del tiempo, pero esto sin hacer ninguna referencia
a las células, a las proteinas de la sangre, a la información
genética, etc. Es decir, desconociendo olímpicamente a los fenómenos
físicos y biológicos que subyacen y que son responsables de este
funcionamiento.

Ahora bien, debe haber alguna correspondencia con la realidad en las
predicciones que se desprenden de los modelos y simulaciones, porque
de lo contrario serían descartados. Las predicciones se contrastan con
mediciones realizadas sobre el sistema real, de modo tal que sólo
resulta aceptable el modelo en tanto ofrezca resultados semejantes
(aunque no iguales) a lecturas obtenidas a partir del sistema
real. Recién cuando se comprueba que el sistema artificial es
capaz de representar al sistema real de algún modo (con ecuaciones
deterministas, con funciones de probabilidad, o con sistemas análogos
-por ejemplo los modelos eléctricos o neumáticos del sistema
cardiovascular), recién a partir de allí se vuelve admisible de
utilizar como herramienta.

Sin embargo hay que advertir que el modelo puede haber sido probado
exitosamente bajo distintas condiciones: considerando arterias con
paredes más o menos elásticas, con volúmenes ventriculares mayores o
menores, con más o menos glóbulos rojos en sangre, etc. De este modo
tenemos un cierto grado de confianza en este modelo, pero esto no
significa que las ecuaciones puedan predecir la evolución del sistema
siempre y para cualquier condición. De hecho, la salida de este
modelo dependerá de ciertas condiciones iniciales, de la aplicación de
estímulos y perturbaciones, etc. El sistema real, dada su
complejidad, nunca puede ser descripto completamente.

Otro elemento que complica las predicciones es la naturaleza aleatoria
de ciertos procesos, por ejemplo en el fenómeno de decaimiento
radiactivo de un nucleo inestable. Podemos saber qué probabilidades
hay de que un átomo decaiga en un momento dado, pero no tenemos
certeza respecto del momento exacto en el que esto efectivamente habrá
de suceder. Es decir, podemos predecir el comportamiento promedio de
un conjunto de átomos, pero carecemos de certeza para predecir qué
sucederá con cada uno de estos átomos a lo largo del tiempo. La
capacidad de describir la realidad y de predecirla se desarrolla, pero
no se puede afirmar que se explica y se comprende el fenómeno en su
totalidad. Sin embargo, la teoría no deja de ser útil.

** Incertidumbre

En ingeniería el error es imposible de erradicar. Si tenemos en cuenta
que necesitamos registrar el mundo real antes de actuar sobre él,
puede parecer catastrófico que no podamos determinar la realidad sin
cometer errores.

Sin embargo el problema se aborda tratando de reducir estos errores y
cuantificando las incertidumbres. En algunos casos el avance del
conocimiento científico y de los desarrollos tecnológicos permite
efectivamente disminuir estos errores, aunque sin eliminarlos
completamente.

Pero en muchos casos hay un problema insalvable, puede suceder que la
propia variable que se pretende medir no tenga un valor exacto, o que
ese valor sea indeterminable, como en el caso de la ubicación y la
velocidad de una partícula sub-atómica, y aún así deben tomarse
decisiones.

¿De dónde proviene esta limitación a la exactitud con que se puede
registrar la realidad? Vamos a usar un ejemplo para mostrarlo. En la
era de los GPS no parece deparar ningún contratiempo determinar la
distancia entre dos ciudades, por ejemplo entre Paraná y Santa
Fe. ¿Hay 30, 35 km?  Puede ser, pero si decidimos no creerle a los
carteles de la ruta y nos proponemos que cada uno de nosotros viaje en
algún vehículo para obtener una medida de la distancia a partir de la
lectura del cuentakilómetro, ¿vamos a llegar todos al mismo resultado?
Cada uno puede hacer el experimento con leves diferencias: ¿cuál
considerará cada uno que es el punto de partida y el punto de llegada?
¿La plaza principal de cada ciudad? ¿El límite de las ciudades según
la legislación?  ¿o la ubicación de las casas más cercanas entre ambas
ciudades? Por otro lado, hemos definido la distancia de la ruta entre
Paraná y Santa Fe, la cual es diferente a la distancia en linea recta
entre ambas ciudades (que tendría también una definición
difusa). Entonces, para el caso de la ruta terrestre, ¿habrán tomado
todos el mismo camino y se habrán desplazado todos por la trayectoria
exacta que recorrieron los demás? Obviamente que si nos reunimos para
comparar resultados nuestras medidas serán distintas, aún cuando todos
contemos con un cuentakilómetros de gran calidad. La propia variable
que queremos medir es hasta cierto punto indeterminada, excepto que
todos acordemos un criterio, de modo que la variable ya no existe sólo
en la realidad sino que la hemos definido en nuestro lenguaje, es
decir que la hemos manipulado o interpretado y ya no es ajena a
nuestra existencia.

Quizás uno puede pensar que ese es un caso particular, ¿y si el
objeto que queremos medir es una mesa?  Aparentemente no tendremos la
dificultad que acabamos de señalar para las ciudades, pero si queremos
tener muy alta precisión en nuestra medida y no nos alcanza con usar
una lupa en cada extremo y amplificamos más y más los bordes, entonces
ya no vamos a ver una superficie que se interrumpe abruptamente, sino
que vamos a poder ver los átomos de la mesa, y sus nubes electrónicas
que además se van a estar moviendo porque incluso en los sólidos hay
agitación térmica.

Tenemos que preguntarnos si efectivamente podremos desprendernos de
estas incertidumbres o si podemos convivir con ellas. La distancia de
Paraná a Santa Fe nos puede servir si queremos calcular cuánto
combustible tener en el tanque (podríamos preguntarnos: ¿cuánta nafta
exactamente consume nuestro vehículo por kilómetro?), o si necesitamos
saber en cuánto tiempo podemos hacer el viaje. En el contexto de esos
problemas, que la distancia varíe en uno, dos o cinco kilómetros no
tiene demasiado impacto. Hay un grado de incertidumbre tolerable en el
conocimiento de la realidad que no afecta nuestra capacidad de actuar
sobre ella. Si queremos saber cuántas personas pueden sentarse
alrededor de la mesa, no tiene sentido tratar de obtener una medida
con la precisión de un Angstrom.

De todos modos creo que este es un tema interesante porque muchas
veces se apela a la ciencia para tratar de resolver temas
conflictivos, y perdemos la noción de que la ciencia no puede
responder cualquier pregunta. Pongamos por caso el tema de la vida
humana: ¿cuando comienza y cuando termina? ¿En qué momento se inicia
la existencia de un ser humano y en qué momento finaliza? Estas
preguntas también requieren criterios (compartidos y con algún grado
de arbitrariedad) para poder ser respondidas.

Lo interesante igual es advertir entonces que quizás la realidad puede
ser medida, comprendida, manipulada, pero hasta cierto punto. Quedará
un borde siempre borroso, aún cuando afinemos nuestros instrumentos de
medición y nuestras teorías. Nunca la certeza podrá ser total.

** Modelos

Otro forma de plantear los límites en nuestra comprensión del mundo a
través de la ciencia surge si analizamos lo que significan los
modelos.

Para dar un ejemplo de modelos consideremos un conjunto de ecuaciones
que pueden usarse para simular la evolucion de la distribución de
calor en un sólido. Este modelo matemático podrá predecir la
temperatura en cualquier parte del cuerpo siempre que se conozcan
ciertas características del medio (su densidad y coeficiente de
transmisión del calor), las condiciones iniciales (cuál era la
temperatura en cada punto en un tiempo inicial arbitrario) y las
condiciones de contorno (cuál es la temperatura del medio en el cual
se encuentra el sólido que modelamos). Se puede predecir así la
evolución de la temperatura en cada punto y en cada momento aún sin
conocer exahustivamente los mecanismos físicos de la transferencia de
calor.

Se suelen utilizar modelos que representan la realidad, es decir que
nos indican el comportamiento de las variables que nos interesan, aún
cuando no haya una explicación convincente de la realidad que se
representa. Por otra parte sabemos que modelos distintos pueden dar
las mismas respuestas frente a las mismas entradas. Nuestro
conocimiento de la realidad a veces es bastante opaco y aún así
suficientemente poderoso.

Se puede tener un modelo de un fenómeno sin comprender el fenómeno en
sí. A pesar de esta carencia igual se obtiene información que será
util para poder actuar. Podemos elaborar sistemas artificiales que
representan el funcionamiento de los sistemas naturales, a pesar de
que la estructura con la cual están construidos sea absolutamente
diferente.

En algunos casos, pueden sintetizarse sistemas que aprenden y que
logran adquirir un conocimiento que no es directamente expresable en
nuestro lenguaje. Es decir que podemos construir máquinas que pueden
desarrollar conocimiento sobre la realidad (como las redes
neuronales), pero que no nos pueden transmitir ese conocimiento. Es
como la materialización del comentario que puede escucharse en las
aulas de ingeniería: "no importa saber sino que importa tener el
teléfono del que sabe". En este caso, podemos construir "máquinas que
saben" y usarlas aún cuando no nos pueden explicar lo que saben.

** Pragmatismo

A modo de conclusión, la condición de verdad que reina en el dominio
de la ingeniería es el pragmatismo. En tanto un instrumento o un
proceso ofrece los resultados deseados entonces resulta aceptable. En
general los desarrollos tecnológicos están orientados a resolver
necesidades, así que el desarrollo de todo lo que cumpla con la
función para lo que fue pensado resulta aceptable. No hay aquí
requerimientos de ajuste a una realidad verdadera y cognoscible, sino
la necesidad de cumplir con ciertos fines.

* Enseñanza

Como la realidad es compleja, y son complejas las teorías que usamos
para explicarla, no siempre resulta facil llegar a la verdad durante
el trayecto de enseñanza. Por ejemplo: no se puede enseñar física
partiendo de la teoría de la relatividad. Empezar por la mecánica
clásica es una elección pedagógica mucho más razonable, y de hecho es
tanta la comprensión que es posible tener del mundo con "sólo" la
mecánica clásica que se puede ejercer la profesión sin siquiera estar
enterado de la existencia de la mecánica relativista.

Tenemos la sensación, al estudiar ciencias, por el modo en que se
presentan los conocimientos, de que las distintas disciplinas tuvieron
un progreso continuo y sus teorías conforman un cuerpo explicativo
coherente, sin fisuras. Suelen estar ausentes los problemas y
deficiencias asociados con cada teoría, no se menciona la existencia
de teorías rivales ni los conflictos asociados con ellas. En
este sentido la enseñanza es a-histórica. De esta manera, los
estudiantes (que luego se convertirán a su vez en docentes que
desconocen la historia de su disciplina) pueden llegar a tener una
percepción equivocada y sobredimensionada sobre su real conocimiento.

Otro conflicto con la verdad tiene que ver con el objetivo que se dan
para sí mismas instituciones como las facultades de ingeniería. Son
discutibles los propósitos a los cuales está orientada la
enseñanza. Más allá de los documentos oficiales y sus bienaventuradas
promesas, los profesores tratan de formar a los estudiantes para que
puedan responder a los problemas esperables en las distintas areas en
la que supuestamente son expertos. Enseñar de esta manera tiene el
peligro de cristalizar formas convencionales de actuar, repetir las
soluciones evadiendo lo que de particular tenga cada problema. Hay en
esto una especie de adoctrinamiento, un recorte a la creatividad, una
falta de compromiso con la crítica. En general pretendemos que los
estudiantes puedan afrontar tareas de diseño, producción y
mantenimiento en relación con la electrónica, instalaciones
hospitalarias, informática, fabricación de implantes, etc. La verdad
sufre en este contexto recortes porque:

a. no hay tiempo físico para formar con profundidad en tantas
especialidades distintas que conforman las carreras profesionales ni
para el abordaje de la complejidad de los temas. Pretendemos enseñar
pero lanzados en una carrera que nos deja sin aliento. Hay que cumplir
con contenidos mínimos que no son tan mínimos, y además hay una
sucesión de asignaturas que exigen de la anterior una serie de
conocimientos que provocan el abultamiento del currículum.

b. no hay mucho espacio para la creatividad, la exploración, el error,
la experimentación real y MUCHO MENOS para cuestionamientos.

c. no hay pretensión revolucionaria en la formación: el mercado de la
salud y la industria se ignoran o se toman como dados. Quizás el
problema de la salud sea resuelto mejor discutiendo políticas
alimentarias, regímenes diferentes de trabajo, modos de producción
menos contaminantes. Sin embargo, nada de esto suele aparacer.

d. si bien se promueve la idea de que el conocimiento racional es
central, la legitimación del saber proviene de la autoridad de los
profesores o de quienes evalúan a los profesores y a las instituciones
educativas.

Si miramos las industrias, las instituciones de salud públicas y
privadas, los organismos de control en los que se desempeñan los
bioingenieros, vemos que la mayoría de los egresados de la facultad
cumplen exitosamente con lo que se les pide hacer. Esto que es visto
como positivo por las autoridades de la universidad, significa también
que la formación profesional cumple en reproducir la mano de obra que
requiere el mercado: especializada, adaptada al mercado y sus
necesidades, incapaz de imaginar y motorizar cambios
significativos. Es lo razonable tratándose de una institución del
Estado.

* La insuficiencia de la verdad para la acción

La posibilidad de discernir la realidad importa para permitirnos tomar
decisiones. Esto es así tanto para todo desafío de la ingeniería como
también para nuestra vida personal y social. Necesitamos tomar
decisiones y allí el conocimiento es vital para decidir de la mejor
manera, comprendiendo los riesgos y beneficios de toda
acción. Los conocimientos científicos resultan así indispensables.

No voy a ahondar en las ventajas del conocimiento científico respecto
de la religión o cualquier otra forma de dogmatismo. Sino que me
interesa plantear las dificultades que presenta dejarse llevar por el
espejismo que del lado de la ciencia no hay más que razón. Planteo
algunos ejemplos locales:

- hace algunos años se discutió a nivel nacional y en particular en la
  UNER la llegada de fondos provenientes por ley, de la Minera La
  Alumbrera, una megamina a cielo abierto ubicada en Catamarca, de la
  cual se extrae cobre, oro y molibdeno. A pesar del rechazo social
  sustentado en diversos cuestionamientos respecto de la contaminación
  producida y sus consecuencias sobre la salud de las personas y el
  medio ambiente, si uno mira la documentación de la megaminera
  encuentra que cumple con estándares internacionales en gestión del
  medio ambiente y en seguridad alimentaria (ISO 22000, ISO 14001,
  etc). Además recuerdo que contaba con el apoyo de instituciones
  vinculadas al quehacer de ingenieros y científicos, como una
  asociación de geólogos de tucuman y distintas universidades, que al
  día de hoy realizan visitas con alumnos de las carreras de Geología
  Minera (UBA), Higiene y Seguridad (UNTucumán), Recursos Naturales y
  Medio Ambiente (UNSalta), etc.

- en Entre Ríos tenemos los temas ambientales de las pasteras sobre el
  Río Uruguay, la instalación de termas, el fracking, la producción de
  transgénicos. En todos los casos aparecen especialistas,
  organizaciones, publicaciones científicas a favor y en contra,
  cuestionando los experimentos, los métodos, los resultados, las
  conclusiones.

- el caso de la soja es un ejemplo de controversia donde se advierte
  la complejidad del análisis de un problema particular. El problema
  tiene muchas aristas y no alcanza para decidir el comprenderlo
  exclusivamente desde una sola disciplina (por ejemplo a través de la
  biología celular o la embriología): se puede analizar la toxicidad
  del herbicida y llegar a conclusiones diversas y contradictorias:
  que no provoca efectos adversos en humanos, que sí los provoca aún
  frente a exposiciones ínfimas pero crónicas, que en realidad el
  glifosato actúa sobre la flora intestinal, que lo que hace daño no
  es el glifosato sino la batería de químicos que lo acompañan, que el
  problema es el gen transgénico de la soja al incorporarlo a la
  dieta, que los transgénicos hacen el mismo daño que otros alimentos,
  que otros alimentos son también transgénicos, que no se puede
  demostrar correlación entre cancer y cultivos de soja porque no se
  puede individualizar su efecto puesto que el origen de las
  patologías puede ser otro, etc. Uno podría pensar que existe una
  microverdad asociada con cada pregunta, o con cada subproblema, pero
  incluso en ese caso pueden plantearse ideas y experimentos que
  arrojarán resultados contradictorios. Es decir, se puede llegar al
  extremo de hacer trampa al diseñar los experimentos, o al analizar
  los resultados. ¿Qué dirán en este caso los empiristas? ¿Cuál será
  el experimento crucial a realizar?  Por otro lado: ¿confiaríamos en
  el juicio de uno o varios expertos?  Por supuesto no estoy
  mencionando cómo afecta a la búsqueda de la verdad la presencia de
  intereses no-científicos. Claramente aparecen posturas de
  científicos e instituciones científicas a través de las cuales se
  traslucen motivaciones e intereses personales, corporativos,
  intereses sociales, económicos, etc.

- La energía nuclear: la ciencia no puede decir si la energía nuclear es
  segura o no es segura. Sí nos puede indicar y describir algunos de
  sus riesgos y ventajas. Nos puede mostrar alternativas o la falta de
  ellas. Pero no es la ciencia la que tiene que aprobar o no
  algo. Porque cuando decimos que la ciencia aprueba o no algo lo que
  estamos diciendo es que las instituciones científicas lo hagan. Y
  como las instituciones científicas son una construcción humana
  atravesada por intereses políticos y económicos, podemos tener a los
  científicos del Conicet coincidiendo con Lino Barañao respecto de la
  inocuidad de los procesos productivos de Monsanto, Barrick Gold,
  Botnia y Chevrón.

* Conclusiones

Algunas conclusiones generales y desordenadas:

- lo que caracteriza al conocimiente científico no es el método sino
  la voluntad de saber a través de la razón, es la exahustividad de la
  búsqueda.

- Es dificil pensar la ciencia aislada de las instituciones en las
  cuales se desarrolla y del contexto en el que lo hace. 

- La racionalidad técnica no puede ser el único árbitro de las
  acciones humanas.

- Una ventaja respecto de otras formas de conocimiento es que evita el
  estancamiento, trata de avanzar en un conocimiento más profundo,
  mientras que formas tradicionales de conocer parecen tender a
  estancarse y reproducir infinitamente lo mismo. 

El problema de la falta de compromiso de los lectores y el hecho de
que no se desencadenen escándalos con consecuencias reales es también
un problema para la ciencia, si pensamos que la ciencia no debe ser
dominio exclusivo de los científicos sino de un público (ilustrado)
general. ¿Qué nos toca hacer frente a esto? Yo creo que hay que
criticar sin piedad al sistema científico, sin endiosarlo por sus
logros, y mostrar que el público general puede participar de sus
procesos, que no incluyen sólo la producción del conocimiento sino su
difusión, la participación en la selección de problemas relevantes, la
auditoría de las instituciones, etc. Por eso es importante una
educación que permita a las personas participar adecuadamente en estas
tareas.

Pensemos en el sistema científico y en cómo su producción no
solamente sirve para brindarnos celulares y vehículos a precio
accesible, sino una batería de muletas para el modo de producción
capitalista.

** La autocrítica en ciencias. El contacto con otras tradiciones.

Algo que me parece imprescindible para el espíritu científico es
advertir las debilidades de las propuestas que uno hace, de las
teorías que uno tiene. Recibir la crítica y evaluarla y no empezar
por ridiculizarla, sino por tratar de entender desde la óptica del
otro. Muchas veces esto puede conducir igual a reafirmar lo que uno
piensa, pero quizás no siempre. Se puede aprender de puntos de vista
no expertos o no especializados (por ejemplo en quienes pueden
elaborar sistemas de comprensión basados en el uso de
analogías). Todas las tradiciones pueden aprender de otras, unas
disciplinas pueden aprender de otras, de otras culturas y formas de
pensamiento. La realidad es tan rica que quizás tiene aspectos que no
son binarios, en los que podrían ser aplicables lógicas diversas. O
hay que advertir que el binarismo es posible siempre que permita
cierta flexibilidad (¿qué onda con los sexos, no es acaso absurdo
plantear la pregunta sobre si una persona es mujer o varón?).

De Feyerabend: pg4. En respuesta a si es deseable apoyar la ciencia
como único camino para comprender el mundo, responde que no y que hay
dos razones para ello: "La primera consiste en que el mundo que
deseamos explorar es una entidad en gran medida desconocida. Debemos
por tanto mantener abiertas nuestras opciones y no restringirlas de
antemano. ... ¿Quién garantiza que [las prescripciones
epistemológicas] constituyan el mejor camino para descubrir, no ya
unos cuantos "hechos" aislados, sino ciertos secretos profundos de la
naturaleza? La segunda es que una educación científica como la
descripta antes (y como se imparte en nuestras escuelas) no puede
reconciliarse con una actitud humanista".

Los defensores de la ciencia suelen apelar a la mejora en la salud y
el confort como elementos propagandísticos. Pero si hablamos de
aportes, también hay que mencionar los transgénicos, las armas, los
desastres nucleares, la contaminación ambiental y demás.

En la película Unbelievers, Dawking y Krauss mencionan que les
gustaría que durante sus vidas aparezca alguna teoría plausible sobre
el origen del universo o sobre alguna cosa así, y que puedan decir:
"oh, era una explicación tan simple y plausible...". Sin embargo, la
idea de que las reglas del universo son simples y elegantes es
absurda, porque está lleno de mecanismos estrambóticos y dificiles de
entender como la relatividad. ¿Por qué un mundo complejo debe
explicarse y entenderse de manera simple?

---

Todas estas cuestiones suelen estar ausentes de la conciencia que
tienen los científicos de sus prácticas, así que cuando opinan de los
métodos de la ciencia, de la fortaleza de sus argumentos, suelen
expresar una visión bastante simplificada de la actividad científica,
aunque sí son capaces de advertir, porque lo experimentan
permanentemente, los mecanismos políticos y económicos que atraviesan
la actividad que llevan adelante.

En general los científicos de la actualidad carecen de formación en
filosofía y en historia de la ciencia, puesto que toda la energía se
proyecta sobre la especialización en la disciplina desde la cual
deberán pelear por becas y subsidios. No creo que actualmente se
valore significativamente el disponer de herramientas ajenas a la
especialidad, ya que no se advierte que la epistemología, la
filosofía, la historia puedan aportar algo a la producción
científica. Habría que contrastar esto con la realidad de los físicos
de la primera mitad del siglo XX.

** Beneficios del avance tecnológico

Respecto de los beneficios de la ciencia, el hecho de tener
celulares, medicamentos, etc.

cómo se distribuye el dinero en ciencias? qué campos reciben más, qué
lineas de investigación se apoyan más?
