#+TITLE: La única verdad es la incertidumbre
#+DESCRIPTION: Apuntes personales acerca del conocimiento en las ciencias
#+AUTHOR: Diego Fainstein
#+DATE:
#+OPTIONS: toc:nil

#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LANGUAGE: es
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}


*Apuntes personales acerca del conocimiento en las ciencias*

* Aclaración

\Large Me parece importante aclarar que mis reflexiones están construidas
desde lo que sería una "visión del usuario", a partir de mis
experiencias laborales y mis lecturas. Esto es diferente a una
exposición hecha por un experto, que en este caso sería un
epistemólogo. No voy a citar a Habermas, ni a Marcuse, ni a Hegel,
exclusivamente porque no los he leído. Sin embargo, la palabra de los
expertos no es la única que puede contribuir a la construcción del
conocimiento, así que los invito a escucharme y a dialogar o debatir.

Siempre es posible que algunas de mis observaciones puedan ser
consideradas superficiales, superadas o directamente erroneas. En ese
caso, espero que estén atentos y lo señalen, tanto durante la
exposición como al final.

También quiero advertir que mi expectativa es cuestionar algunas
perspectivas demasiado idealizadas acerca de las ciencias, que se dan
justamente en los ámbitos en que he trabajado. Mis reflexiones surgen
en respuesta a un modo extendido de pensar acerca de la ciencia, la
tecnología y la enseñanza. Mi propósito con esta presentación es
discutir esas concepciones para que nadie esté cómodo ni afirmando
que el conocimiento científico (del modo en que lo conocemos) es
despreciable ni encumbrándolo como a un ídolo único e indiscutible.

Esto me preocupa un poco porque en el mundo se extienden y fortalecen
distintas formas de fundamentalismo e irracionalidad, con lo cual
parecería que es irresponsable cuestionar a aquello que se identifica
con la razón y la libertad. Sin embargo acallar la crítica agitando el
equivalente al /fantasma de la derecha/ nos convertiría justamente en
aquello que rechazamos.

* Mis ámbitos de trabajo.

Voy a presentar algunas ideas en relación con mis espacios de
trabajo, actuales y pasados, por lo que me parece importante para
situar a todos en el contexto en el que se desarrollan estas
reflexiones, describir brevemente estos lugares y sus características
sobresalientes, los cuales constituyen entornos donde el concepto de
verdad cobra distintos significados o tiene diferentes alcances y
particularidades.

** Enseñanza

Empecé como auxiliar-alumno en 1998, en la carrera de
Bioingeniería. Actualmente soy Jefe de Trabajos Prácticos en dos
asignaturas: Bioingeniería II y Medicina Nuclear (de acuerdo a la
nomenclatura del Plan 1993). La primera aborda las técnicas para
obtener y procesar información del mundo real y en particular del
cuerpo humano (se estudian los modos de medir la temperatura, la
presión arterial, la actividad eléctrica del corazón en la forma del
electrocardiograma, etc) mientras que la segunda se ocupa de los usos
de las radiaciones ionizantes para diagnóstico (es decir para la
obtención de imágenes del cuerpo humano) y para tratamiento
(principalmente del cancer).

** Investigación y Desarrollo

Participé en tareas de investigación en el campo de la
electrofisiología cardíaca.

Trabajé dentro de grupos que se ocupan de dos grandes temas:

  1. Uno es la variabilidad de la frecuencia cardíaca: a partir del
     registro del electrocardiograma mediante electrodos superficiales
     se calcula la frecuencia cardíaca, que va variando latido a
     latido, y se trata de correlacionar esa información con diversos
     estados fisiológicos y fisiopatológicos (como el estrés), para
     obtener un índicador clínico de la condición de salud o
     enfermedad del paciente.

  2. El otro tema es el fenómeno de excitación-contracción: se trata
     de indagar en los mecanismos celulares involucrados desde que
     llegan los impulsos nerviosos a las células cardíacas, hasta que
     éstas se contraen, y logran en conjunto y coordinadamente que el
     corazón realice su función de bomba.

*** División del campo

Voy a presentar algunas ideas sobre la verdad diferenciando entre
especificidades en estos tres campos: ciencias, tecnologías y
enseñanza.

Quería aclarar que la división es arbitraria y tiene más que ver con
tratar de presentar las ideas en forma ordenada y secuencial que en
hacer una diferenciación analítica seria. Las tareas de investigación
/pura/ y de desarrollo de tecnología están relacionadas y se necesitan
mutuamente.

En general las ideas más difundidas y discutidas de las diferentes
escuelas epistemológicas, desde el positivismo en adelante, se
refieren a las ciencias puras, es decir aquellas que se ocupan de
descubrir cómo es el universo, cómo funciona la naturaleza, y
demás. Para ellas se plantean y se discuten, por ejemplo, diferentes
modelos metodológicos.

El desarrollo de tecnologías o las ciencias aplicadas (que son los
viejos oficios pero profesionalizados, y que podemos llamar /ciencias
del diseño/) tienen particularidades, ya que su objetivo no es tanto
comprender el mundo sino operar sobre él, mediante la creación o
modificación de procesos o instrumentos para cambiar nuestro entorno.

Debe tenerse en cuenta que esta diferenciación se vuelve difusa dado
que las ciencias básicas requieren de tecnologías más sofisticadas
para permitir la realización de experimentos, mientras que el
descubrimiento de las leyes naturales habilita al avance de las
ciencias del diseño.

En ambos casos mi participación principal tuvo más que ver con la
construcción de instrumentos de medición para obtener información en
cada uno de estos dos campos. No trabajé directamente en la
elaboración de teorías y experimentos, sino en posibilitar estos
últimos, pero en ambos estuve en contacto con investigadores /básicos/
y sus discusiones acerca de las incógnitas del campo de estudio, las
teorías que pretendían probar o cuestionar y los experimentos para
materializar estos propósitos.

* Ciencia y realidad

En los ámbitos que conozco las personas son realistas duras, que
asumen la existencia de una realidad objetiva, independiente de los
seres humanos, de nuestros deseos, de nuestros sentidos. La mayoría,
sino todos, creen que la realidad es tal cual la registramos con
nuestros equipos. Los instrumentos nos muestran lineas que se dibujan
en el monitor o números en el panel frontal de un amplificador, y a
través de ellos vemos (o quizás imaginamos) proteinas cambiando de
forma, iones que se desplazan a través de una membrana, impulsos
nerviosos que chocan con células muertas. Entrenados en la
interpretación de estas observaciones, se desarrolla una familiaridad
con las teorías que permite ir comprendiendo los fenómenos con una
profundidad cada vez mayor. En lo que Kuhn llamaría un período de
ciencia normal vamos desarrollando progresivamente el conocimiento
mediante teorías y experimentos cada vez más explicativos. No advierto
instrumentalismo: lo que registramos es lo que existe en realidad, hay
correspondencia entre nuestras afirmaciones y la estructura de lo que
investigamos.

Los experimentos se diseñan para obtener información útil sobre un
proceso. Para ello se establecen condiciones de manera que la
variación controlada de un solo parámetro sea el que provoca los
cambios que se pueden registrar con los instrumentos de medición. Por
ejemplo, se registra la diferencia de potencial entre el interior y el
exterior de una célula, manteniéndola inmersa en una solución que la
mantiene con vida, pero siempre con el mismo pH, las mismas
concentraciones de glucosa, bicarbonato, etc. De este modo se puede
investigar, por ejemplo, cómo responde el potencial a cambios en la
temperatura, sabiendo que los cambios no pueden deberse a variaciones
en el contenido de la solución fisiológica. La información obtenida se
analiza en busca de relaciones entre la variable testeada y distintos
parámetros del registro, con el propósito de encontrar correlaciones y
causalidades. También se realizan experimentos para ver el mismo
fenómeno con diferentes técnicas, lo cual puede ofrecer información
nueva. Si el planteo de un experimento fuera caótico, o si estuviese
diseñado inadecuadamente, los resultados no permitirían concluir nada.

De acuerdo a lo que se investiga, la realidad puede describirse con
esquemas, ecuaciones, modelos, analogías, fotografías, registros
temporales de la evolución de distintas variables, reglas, tablas de
probabilidades, etc.

Si un fenómeno ocurre tiene una o varias causas y distintos efectos, y
no tiene mucho sentido realizar suposiciones que resulten irracionales
a la luz de nuestros saberes actuales. Esto es así porque se pretende
cierta eficiencia en el proceso de develar lo desconocido. Hay un
marco teórico a la luz del cual se interpretan los resultados. Si hay
que describir cómo se limita la cantidad de iones de calcio que
ingresan a la célula cardíaca cuando llega un impulso nervioso, una
explicación relacionada con las fuerzas sutiles del lado oscuro o con
la memoria cuántica de la flecha del tiempo sería impublicable, salvo
en revistas literarias, o en revistas de dudosa calidad científica. Se
supone también que la naturaleza funciona con regularidad, es decir
que --por ejemplo-- un canal de calcio tiene siempre la misma cinética
en condiciones semejantes y hay ciertas limitaciones en cuanto a las
variables a las cuales podemos atribuir participación en el fenómeno,
de acuerdo al conocimiento actual.

No hay en este esquema de trabajo lugar para afirmaciones relativistas
extremas, tales como que es válida cualquier interpretación laxa de
los resultados obtenidos. Primero por la suposición realista de que la
naturaleza funciona de alguna forma coherente y regular (incluyendo
los fenómenos probabilísticos y caóticos que también presentan rasgos
de coherencia y regularidad), y segundo por la evaluación a la que es
sometida la investigación y de la cual depende su aceptación y
posibilidad de continuidad. Si bien los científicos aceptan que las
teorías tienen diverso grado de aproximación a la realidad, que lo
establecido está sometido a cambios, y se entiende que los modelos
descriptivos o explicativos pueden mejorarse, no se advierten estas
salvedades en las conversaciones cotidianas.

Los jueces de esta verdad son los pares, principalmente los revisores
de los artículos que aparecen en las revistas especializadas y también
los evaluadores en las instituciones que otorgan el presupuesto para
continuar las investigaciones. Frecuentemente cuando un artículo es
rechazado o cuando se pierde un subsidio se duda sobre la
imparcialidad o la pericia de los evaluadores antes que de la
debilidad de los propios argumentos. No voy a desarrollar estos
aspectos sociológicos de la investigación científica, aunque me
resultan muy interesantes y explicativos de la actividad.

** Problemas reales

La adecuación a ciertas normas metodológicas y de razonamiento
intentan depurar el conocimiento de charlatanería e imprecisiones, de
manera tal que se puedan establecer conocimientos sólidos para el
avance en la comprensión de las distintas disciplinas, y así
traducirse finalmente en una mejor comprensión del universo.

Pero vamos a plantear algunas dificultades. Da la impresión de que no
hay mucho lugar para las contradicciones, o que éstas son facilmente
eliminables en base a la experimentación y a la contrastación
intersubjetiva por parte de la comunidad de pares.

Sin embargo los resultados experimentales no siempre son fáciles de
analizar. A veces la información dice una cosa en un conjunto de
experimentos y otra muy distinta al analizar iguales experimentos
realizados en las mismas condiciones, y no se sabe de dónde proviene
la divergencia. ¿Hubo algún error en la concentración de una solución?
¿Hubo problemas con el instrumental de registro?  ¿Estuvo la persona
encargada del experimento realmente atenta y anotó todo lo ocurrido?
¿El tejido donde se realizó el registro se preparó sin causarle daños?
Muchas cosas pueden salir mal y suele destinarse mucho tiempo a
depurar los experimentos, ajustar los instrumentos para que su
funcionamiento sea sólido, consistente, inmune a las perturbaciones.

Cuando se obtienen resultados dispares, al utilizar las mismas
herramientas o al usar diferentes metodologías para analizar el mismo
proceso, el motivo de la disparidad puede estar en que efectivamente
se estén produciendo errores sistemáticos (que se podrán solucionar
respondiendo a preguntas como las que formulé recién) o puede ser
que la evidencia sea efectivamente caótica porque el sistema que se
analiza tiene una complejidad tal que pequeñas variaciones en un
parámetro producen grandes efectos, o quizás la presencia de una
variable desconocida tiene una influencia que no podemos advertir, o
incluso puede ser que la teoría que subyace a nuestras observaciones
no nos permite valorar adecuadamente lo que observamos. Tengamos en
cuenta que lo que observamos a través de nuestras sensaciones e
instrumentos está sometido a la interpretación que hacemos de los
datos, para lo cual siempre estamos utilizando teorías, nos demos
cuenta de esto o no. Y estos no son los únicos problemas que pueden
aparecer.

*** Ejemplo: geo y heliocentrismo.

Para ilustrar esto voy a comentar brevemente uno de los ejemplos más
paradigmáticos respecto de la oposición entre ciencia y religión. Desde
el siglo IV(ac) hasta el siglo XVI se mantuvo mayoritariamente aceptado el
modelo geocéntrico propuesto por Ptolomeo y Aristóteles, el cual
contaba con la bendición de la Iglesia Católica y su eficaz máquina
propagandística, incluyendo la técnica publicitaria conocida como
Inquisición (ja). Durante el Renacimiento, Galileo construye varios de
los primeros telescopios (aunque no es su inventor) y realiza
observaciones (como por ejemplo de las lunas de Jupiter) que permiten
cuestionar el modelo geocéntrico. A pesar de que conocemos el
desenlace, y sabemos que la teoría geocéntrica es incorrecta, voy a
utilizar el ejemplo para mostrar que las observaciones de Galileo y de
sus oponentes no eran necesariamente evidentes, obvias y fáciles de
aceptar. Con esto pretendo mostrar cómo el relato simplificado de los
hechos que lleva a colocar en el lugar del absurdo las posiciones
geocéntricas le otorgan al empirismo una fortaleza inmerecida.

Hay al menos dos aspectos del problema que me gustaría plantear:

*Punto 1* Los conocimientos de óptica de Galileo no eran suficientes
para que resultaran incuestionables las observaciones hechas con el
telescopio. Una cosa es que se haya podido comprobar que este nuevo
instrumento ampliaba una imagen conocida dentro de la Tierra,
y otra es que pudiese funcionar de manera confiable para observar
objetos celestes. Por ejemplo: ¿era posible entender qué significaban
las distorsiones de los sistemas primitivos de lentes o sospechar el
efecto de la refracción en la atmósfera terrestre? ¿Acaso pensamos que
los telescopios de Galileo ofrecían una calidad de imagen comparable a
los disponibles en la Asociación Entrerriana de Astronomía?  Gran
parte de la física óptica necesaria para comprender el telescopio no
estaba al alcance de Galileo y fue desarrollada después. Además las
observaciones eran inconexas también con las predicciones de la teoría
copernicana, por ejemplo el hecho de que las dimensiones de los
planetas a lo largo de su órbita no coincidían con las diferencias que
anticipaba esta teoría.

Para plantear una analogía podríamos sustituir el instrumento
"telescopio" por el instrumento "Wikipedia". Si no supiésemos cómo
funciona quizás empezamos a usarla para buscar ciertas definiciones y
vemos que los resultados que nos ofrece coinciden con información que
ya conocíamos o que previamente buscamos en otra
enciclopedia. ¿Alcanza con eso para confiar en que toda la información
que en adelante busquemos en Wikipedia será veraz?  Por supuesto que
no, y esto no quiere decir que la información de la Wikipedia no sirva
para nada. Podemos resumir todo esto afirmando que la observación no
es independiente de la teoría, que lo que observamos está condicionado
por lo que sabemos. Otro ejemplo: imágenes obtenidas del cuerpo humano
mediante rayos X, tomografía computada, resonancia magnética,
tomografía de emisión de positrones y demás, nos brindan información
que no todos estamos en condiciones de interpretar y además, aquellos
que sí lo están, no siempre pueden efectuar lecturas carentes de
errores a partir de ellas o lecturas coincidentes entre sí. Siempre
hay una interrelación entre observación y teoría, con lo cual parece
razonable decir que las observaciones que fortalecen o debilitan los
puntos de vista en conflicto nunca son completamente puras. En el
lenguaje de la epistemología se suele decir que las observaciones
están imbuidas de teoría.

*Punto 2* En segundo lugar, volviendo al ejemplo de Galileo, se puede
afirmar que había elementos empíricos también en el campo de los
aristotélicos. Por ejemplo: para sostener que la Tierra no se movía
planteaban el siguiente experimento. Si se deja caer una piedra desde
una torre muy alta y la Tierra se mueve, sería razonable que la piedra
no cayese sobre la base de la torre, sino a una distancia relacionada
con el movimiente de la Tierra durante el tiempo en que se produjo la
caida. Otro argumento en el mismo sentido: si dos proyectiles se
lanzan en direcciones opuestas con la misma fuerza, deberían recorrer
distinta distancia. Faltaba la noción de inercia, para explicar estos
dos hechos contradictorios con la tesis heliocéntrica. Lo que muestran
estos ejemplos es que la obviedad de una hipótesis recién se logra
mucho tiempo después de que teorías rivales disputan cuál es aquella
con mayor contenido de verdad.  Con esto podemos apreciar que cuando
el conocimiento trata de expandirse sobre terreno desconocido se
enfrenta con desafíos que no son tan triviales de resolver como con el
mecanismo de la falsación. Quizás estas reflexiones nos permitan
esquivar el peligro de convertirnos en dogmáticos defensores del
empirismo.

Para un estudio detallado de cómo se dio la conversión del
geocentrismo al heliocentrismo se puede leer "Tratado contra el
método" de Paul Feyerabend.

En conclusión, la contrastación empírica parece cobrar más fuerza
cuando ya se ha desarrollado la teoría, y cuando no se trata solamente
de un solo tipo de observación sino que ya existe un entramado de
argumentos que fortalecen un modelo explicativo por sobre otro.

** Sistemas complejos: especialización y holismo.

*** Introducción

La ciencia logra una comprensión relativamente profunda de algunos
aspectos de la realidad. En algunos casos nos resulta evidente la
correspondencia entre las consecuencias que podemos experimentar
respecto de una teoría y la propia realidad. ¿Es aceptable cuestionar
la ciencia teniendo en cuenta sus logros? ¿Nos convierte eso en
apóstatas que en aras de la coherencia deberían renunciar a los
tratamientos médicos modernos y al uso del whatsapp? Para mi no se
trata de rechazar esta forma de conocer sino de advertir que hay
distintos niveles de verdad en el conocimiento científico. Cuando se
trabaja sobre un sistema complejo, se pueden hacer afirmaciones
verdaderas, pero cuyo alcance descriptivo o explicativo tiene límites.

*** La complejidad del fenómeno de excitación-contracción

Para estudiar el fenómeno de excitación-contracción hay muy diversas
técnicas y aproximaciones. Se pueden realizar mediciones eléctricas u
ópticas, con preparados de células aisladas o sobre porciones de
tejido o incluso en corazones enteros, sobre diversos modelos
animales: ratón, conejo, rata, cerdo, etc. Algunos métodos se utilizan
mucho porque son relativamente económicos o fáciles de implementar, o
porque el éxito de alguna investigación les dio impulso y se
popularizaron. Pero justamente ocurre lo siguiente: los resultados
obtenidos son contradictorios. Lo que sucede en la célula aislada es
diferente a lo que sucede en el corazón completo, y por lo tanto, lo
que se descubre sobre los mecanismos en un nivel de organización
celular no es tan fácil de extrapolar para comprender lo que sucede en
el órgano completo. No quiere decir que lo que averiguamos tras
fraccionar el sistema es inútil, sino que es limitado lo que podemos
saber si sólo hacemos estudios analíticos.

*** La medicina y la materialidad ingenua

Esto que sucede a nivel celular y tisular se amplifica cuando tratamos
de comprender los macrosistemas. Al considerar el cuerpo completo de
una persona es indeterminada la cantidad de variables
interrelacionadas que tienen efecto sobre la porción del cuerpo que
pretendemos investigar. Es necesario un estudio de las partes, pero el
funcionamiento de la totalidad no es solamente la suma del
funcionamiento de las fracciones. En el sistema completo (algo
también aplicable a los sistemas sociales) se dan interacciones
múltiples y complejas que modulan el comportamiento de los componentes
individuales.

Pensemos el caso del cuerpo humano, el cual en la medicina científica
tradicional tiende a explicarse desde una perspectiva
mecanicista. Tras una corta búsqueda en PubMed se pueden encontrar
títulos como estos: /Asociación entre los genes del receptor de
dopamina con la infidelidad y la promiscuidad sexual/, /Correlaciones
neurales del perdón a las transgresiones morales que implican engaño/
(estudios realizados con PET), /La genética de las adicciones/,
etc. Indudablemente hay correlaciones entre la base física y nuestras
emociones y comportamientos, pero hay acá un detalle sobre el que
quisiera ahondar.

El descubrimiento en el mundo occidental, por parte de William Harvey
en el siglo XVII, de que la sangre es impulsada a través de arterias y
venas por el corazón (que funciona como una bomba hidráulica) recién
se logró cuando se desarrollaron los conceptos físicos que permitían
concebir este esquema. Tomar un modelo de un sistema que comprendemos,
para explicar otro aún bajo investigación, puede abrirnos la
posibilidad de grandes descubrimientos. Sin embargo, si nos
entusiasman los excelentes resultados de esta estrategia y nos
quedamos prisioneros de una concepción mecanicista del Hombre,
podríamos llegar a creer que todo puede ser explicado en términos
materiales simples; es decir que el funcionamiento de nuestro cuerpo,
nuestro comportamiento, emociones y decisiones pretendería ser
explicado en función de enlaces químicos, información genética y masas
en movimiento. La vinculación es innegable, pero es insuficiente como
explicación, como instrumento de comprensión.

*** Materialistas analizan una computadora

Imaginemos esta situación: un grupo de materialistas ingenuos se
encuentran una computadora moderna que en su mundo no existe. ¿Van a
ser capaces de explicar el funcionamiento de la misma a través de
mediciones sobre sus componentes físicos? Tras una enorme cantidad de
experimentos muy sofisticados de expertos en la química del silicio,
en física eléctrica, en termodinámica y transferencia de calor, es
evidente que sabrán mucho de las distintas partes de la computadora,
pero desconocerán lo esencial de ella, la existencia de lo que
llamamos software, es decir el conjunto de instrucciones que organizan
el funcionamiento de la máquina. Este software carece prácticamente de
correlato en el mundo físico, y de hecho puede funcionar igual en
distintos soportes (distintos microprocesadores), así que es casi
imposible de ver aún cuando se examine el hardware con microscopios
electrónicos y osciloscopios. En otras palabras, la realidad puede ser
reconocida limitadamente de acuerdo a la utilización de un tipo de
prácticas de investigación. ¿Calificarían de pseudo-científicos a los
que planteasen que el comportamiento de la computadora tiene que ver
con un aparato psíquico inmedible o con un /espíritu/? ¿Será razonable
limitar las teorizaciones sobre el funcionamiento de la computadora a
lo experimentable mediante la interacción con la pantalla y el teclado
(es decir mediante una forma de psicología del comportamiento)? Lo que
quiero mostrar es que hay criterios de demarcación del conocimiento
científico que reducen lo susceptible de conocerse a aquello medible y
de materialidad más ingenua. Concebir la ciencia de esta manera puede
llevarnos a rechazar modos de conocer la realidad más sujetos a la
especulación, y a calificar a aquello que cae fuera de pura
charlatanería.

*** Lenguaje

Un proyecto importante del positivismo fue el de desarrollar un
lenguaje único para la ciencia. Si bien las matemáticas se usan como
herramienta y pueden ser comprensibles para especialistas de diversos
campos, es absurdo pensar que un físico teórico habla el mismo idioma
que un biólogo molecular. Hoy en día, en congresos y encuentros,
da la sensación de que científicos que investigan incluso dentro de
una misma disciplina apenas pueden entenderse, debido al grado de
especialización y las particularidades de cada problema.

Lo más cercano al proyecto unificador podría ser la idea de conformar
equipos de investigación que integren a especialistas de diversas
disciplinas, así se vuelve posible que un mismo fenómeno se estudie
simultaneamente desde distintas perspectivas. Por ejemplo, en el
estudio del fenómeno de excitación-contracción se pueden encontrar
biólogos, bioquímicos, físicos, informáticos, médicos, ingenieros,
veterinarios, etc. Hay herramientas que son comunes y comprensibles
para todos, pero el lenguaje en común está en permanente construcción,
y los significados de ciertos experimentos, o técnicas o resultados
pueden ser difíciles de explicar y compartir.

Todo lenguaje usado para describir o explicar un fenómeno tiene
limitaciones. En informática se han desarrollado enorme cantidad de
lenguajes y dialectos con el propósito de dar mejor respuesta a
diferentes problemas. Por ejemplo para escribir programas de
inteligencia artificial suele usarse Lisp o Prolog u otros
semejantes. No cualquier lenguaje tiene la misma potencia para
resolver todos los problemas informáticos. Del mismo modo, podemos
pensar que la utilización de un lenguaje en particular, sea el
castellano, o el lenguaje de la química, o las matemáticas, limitan la
manera en como pensamos, describimos y explicamos la realidad.

La matemática incluso, como lenguaje aparentemente objetivo, no
garantiza la comprensión:

Por ejemplo, algunas instituciones relacionadas con la educación, como
la propia facultad de ingeniería, utilizan ciertos indicadores
matemáticos para dar cuenta de lo que entienden como /calidad de la
enseñanza/. Cuantifican la relación del número de docentes al número
de alumnos, la cantidad de alumnos aprobados y reprobados en cada
cuatrimestre, y el promedio de las notas. Creen que de esta manera
tienen información sobre el sistema educativo. Por supuesto que logran
construir a partir de estas observaciones una descripción, pero dudo
mucho de que puedan comprender realmente lo que sucede en las aulas.

Otro ejemplo de manipulación de la realidad con herramientas
matemáticas puede ser la descripción de la economía mediante la
selección arbitraria de parámetros.

*** La verdad como un entramado autocoherente.

Hay una imagen que se me presenta cuando imagino la forma de nuestras
concepciones sobre el mundo: la de una tela de araña. Quizás en
algunos casos cuando los sistemas que estudiamos son menos complejos,
efectivamente podamos pensar que nuestras teorías describen a la
realidad tal cual es. Pero en los sistemas más complejos e
interesantes este ajuste es dificultoso de lograr. Es más razonable
pensar que las verdades que podemos producir sólo tienen algunos
puntos de contacto con la realidad mientras que gran parte de nuestras
afirmaciones sólo son verdad en tanto mejoran la coherencia de
nuestros modelos explicativos (esto sería como una postura
instrumentalista) sin que estén tan ajustadas a la realidad. Verdades,
entonces, serían aquellas afirmaciones que tiendan a que el modelo
explicativo sea cada vez más autocoherente, como si estuviésemos
construyendo una tela de araña donde sus puntos de apoyo fuesen las
comprobaciones empíricas y las teorías fuesen hilos que deben
fortalecer la estructura de la tela, aún cuando no necesariamente
brinden muestras inequívocas de estar vinculadas con la realidad.

*** Conclusión

Pretendo señalar que la ciencia puede no abarcar al objeto de estudio
en su totalidad. Debemos ser concientes de las limitaciones que impone
la investigación científica basada en la especialización. No es
tampoco fácil pensar en un modo de producción de conocimientos más
holístico e interdisciplinario que no caiga en la improductividad o el
cualquierismo.  De todos modos está claro el peligro de negar todo
aquello que no se comprende. La investigación científica debería
mantener apertura y flexibilidad, aún cuando se corra el riesgo de
elaborar conocimientos y teorías espúreas.

Lo fundamental en ciencias no me parece que deban ser los métodos de
investigación y el empirismo, sino el apego a la crítica, la admisión
de una pluralidad de ideas en conflicto, y la evasión de toda forma de
dogmatismo. Esto quizás le quita certeza, nos sumerge en un mundo de
incertidumbres, pero le agrega potencia a nuestra capacidad de
conocer. Tener esto presente también nos habilita a reconocer el valor
de las disciplinas que no necesitan ser científicas para producir
conocimiento (la filosofía en general, la metafísica en particular, la
política, psicología, etc).

Por supuesto que toda esta propuesta choca contra el modo en que está
organizado el sistema científico y tecnológico, y los propósitos que
persigue.

* Tecnología, ciencias del diseño

** Introducción
Los bioingenieros que se ocupan del mantenimiento de hospitales y
clínicas, o del diseño de instrumentos para el cuidado de la salud, no
sólo utilizan los vastos conocimientos de las ciencias sino que
también generan saber. Esta característica difumina el límite entre
ciencia y tecnología, y aleja la concepción de tecnología como una
mera aplicación del conocimiento científico.

** Simulaciones y modelos
Una forma particular de construcción de conocimientos es la
utilización de simulaciones y modelos. Con estas herramientas se
sintetizan sistemas cuya estructura no tiene relación con nuestra
realidad, excepto por el hecho de que imitan lo que sucede en nuestro
mundo, de un modo tal que viendo el sistema artificial aprendemos
sobre el mundo real. No es algo novedoso, puesto que las matemáticas
generan modelos desde hace mucho tiempo. Lo llamativo en la actualidad
es la potencia que alcanza este modo de conocer, debido al incremento
de la capacidad de cálculo que brindan las computadoras.

** Modelos como /cajas negras/

Los modelos son representaciones parciales de la realidad, sistemas
que enfocan un aspecto particular del mundo real y que nos brindan
información aún cuando la estructura y los fenómenos internos del
sistema real nos siguen siendo desconocidos. Son una especie de cajas
negras cuyo interior desconocemos, pero que frente a estímulos y
perturbaciones responden como si fueran un trozo de nuestro mundo. Hay
que tener en cuenta que al ser esencialmente distintos, las
similitudes de comportamiento tienen un límite.

Ya dijimos que en el siglo XVII se pudo explicar la función del
corazón y el circuito de la sangre gracias al desarrollo de conceptos
como el de /bomba hidráulica/. Actualmente podemos hacer mucho más,
podemos plantear modelos matemáticos en la forma de sistemas de
ecuaciones diferenciales y obtener resultados numéricos que predicen
la evolución temporal de la presión y el volumen de sangre en cada
porción del sistema. Algo semejante se puede hacer pero con
componentes físicos y tangibles: se puede construir un modelo del
sistema circulatorio con baterías, resistencias, capacitores e
inductancias y a través de la medida de voltajes y corrientes
eléctricas sobre este sistema artificial, se puede tener información
sobre la presión o el volumen de sangre que habría en cada sección del
sistema. Esto es util porque permite experimentar sobre el sistema
artificial sin poner en riesgo la vida de pacientes.

Se pueden construir modelos eléctricos, hidráulicos y neumáticos de
sistemas tan diversos como la economía de una empresa o la evolución
de distintas poblaciones en una cierta región.

La potencia de esta forma de conocer es evidente. Sin embargo lo que
me interesa remarcar es el caracter limitado y parcial de este saber,
no para impugnarlo sino para poder vislumbrar que siguen existiendo
incógnitas en esa realidad que se está analizando.

Aún cuando hay regularidad en la naturaleza, me parece que es
importante no pasar por alto la presencia de la singularidad, que
desde mi punto de vista resulta de la combinación de las leyes
naturales con el efecto de ínfimas diferencias en las condiciones de
estructura y funcionamiento de los objetos aparentemente
idénticos. Para simplificar esta idea podemos pensar en lo que
sucedería si contamos con dos personas idénticas, de modo tal que uno
funcione como modelo del otro. Si medimos la misma variable
fisiológica estando ambas en la misma situación, ¿obtendríamos
resultados exactamente iguales frente a la administración de un mismo
estímulo? La respuesta de un modelo nunca es exactamente idéntica a la
del sistema que representa, por lo que siempre habrá un cierto nivel
de incertidumbre y de desconocimiento en el saber.

** El saber enigmático. Redes neuronales.

Un caso particular de instrumentos para construir conocimientos es el
de algunas formas de inteligencia artificial, como las redes
neuronales. En estos sistemas se tiene una representación matemática
del funcionamiento de una neurona real, con múltiples entradas y una
sola salida. La salida puede tener dos únicos estados: activado o
no-activado, igual que en una neurona real. Se pueden combinar muchas
de estas neuronas artificiales formando una estructura que toma el
nombre de red neuronal. Esta red puede entrenarse para resolver
ciertos problemas o cumplir con cierta función.

Para que la red pueda cumplir con su propósito primero hay que
entrenarla con un conjunto conocido de entradas para las cuales además
conocemos las salidas deseadas. Se evalúan las salidas de la red ante
cada entrada y si hay diferencia respecto de lo que debería haberse
obtenido, entonces se modifican ciertos números llamados /pesos/ que
vinculan las entradas con las neuronas y a las neuronas entre sí. Esto
se hace hasta que la red ofrece las salidas deseadas y ya no es
necesario modificar más estos números.

A partir de ahí la red neuronal podrá cumplir su función, aún cuando
las entradas sean distintas a las utilizadas para su entrenamiento, es
decir que la red puede /generalizar/. Lo que me interesa señalar es
que el conocimiento alojado en esa red neuronal se encuentra
codificado en los /pesos/. Podemos usar ese conocimiento, pero no
tiene ningún sentido interpretar el significado de esos números. Es
decir, la verdad contenida en ese formato nos resulta inaccesible para
nuestra comprensión, aun cuando podamos utilizar ese saber con fines
prácticos.

** Aleatoriedad y caos

Ya vimos que hay cierta singularidad imposible de replicar entre un
trozo de realidad y un modelo o simulación. Otro elemento que complica
las predicciones es la naturaleza aleatoria de ciertos procesos, y el
caos (al menos aparente) presente en todos los sistemas complejos.

Por ejemplo hay aleatoriedad en el fenómeno de decaimiento radiactivo
de un nucleo inestable. Podemos saber qué probabilidades hay de que un
átomo decaiga en un momento dado, pero no tenemos certeza respecto del
momento exacto en el que esto efectivamente habrá de suceder. Podemos
predecir el comportamiento promedio de un conjunto de átomos, pero
carecemos de certeza para predecir qué sucederá con cada uno de estos
átomos a lo largo del tiempo, lo cual puede indicar dos cosas: que el
fenómeno es realmente de naturaleza aleatoria o quizás nuestro
conocimiento es tan limitado que nos parece un comportamiento
azaroso. Lo que me parece interesante es señalar que quizas no hay
modo de saber esto.

La capacidad de describir la realidad y de predecirla se desarrolla,
pero no se puede afirmar que se explica y se comprenden los fenómenos
en su totalidad. Aún así, con estas limitaciones, es notoria la
utilidad del saber.

** Incertidumbre

En ingeniería el error es imposible de erradicar. Si tenemos en cuenta
que necesitamos registrar el mundo real antes de actuar sobre él,
puede parecer catastrófico que no podamos determinar la realidad sin
cometer errores.

Los ingenieros tratan de reducir estos errores y
de cuantificar las incertidumbres. En algunos casos esto es posible,
pero nunca se llega a la completa eliminación de los mismos.

En muchos casos hay un problema insalvable: puede suceder que la
propia variable que se pretende medir no tenga un valor exacto, o que
ese valor sea indeterminable, como en el caso de la ubicación y la
velocidad de una partícula sub-atómica.

¿De dónde proviene esta limitación a la exactitud con que se puede
registrar la realidad? Vamos a usar un ejemplo para mostrarlo. En la
era de los GPS no parece deparar ningún contratiempo determinar la
distancia entre dos ciudades, por ejemplo entre Paraná y Santa
Fe. ¿Hay 30, 35 km?  Puede ser, pero si decidimos no creerle a los
carteles de la ruta y nos proponemos que cada uno de nosotros viaje en
algún vehículo para obtener una medida de la distancia a partir de la
lectura del cuentakilómetro, ¿vamos a llegar todos al mismo resultado?
Cada uno puede hacer el experimento con leves diferencias: ¿cuál
considerará cada uno que es el punto de partida y el punto de llegada?
¿La plaza principal de cada ciudad? ¿El límite de las ciudades según
la legislación?  ¿o la ubicación de las casas más cercanas entre ambas
ciudades? Por otro lado, hemos definido la distancia de la ruta entre
Paraná y Santa Fe, la cual es diferente a la distancia en linea recta
entre ambas ciudades (que tendría también una definición
difusa). Entonces, para el caso de la ruta terrestre, ¿habrán tomado
todos el mismo camino y se habrán desplazado todos por la trayectoria
exacta que recorrieron los demás? Obviamente que si nos reunimos para
comparar resultados nuestras medidas serán distintas, aún cuando todos
contemos con un cuentakilómetros de gran calidad. La propia variable
que queremos medir es hasta cierto punto indeterminada, excepto que
todos acordemos un criterio. Si hacemos esto a esa variable la hemos
definido en nuestro lenguaje, la hemos manipulado o interpretado y ya
no es ajena a nuestra existencia.

Quizás uno puede pensar que ese es un caso particular, ¿y si el
objeto que queremos medir es una mesa?  Aparentemente no tendremos la
dificultad que acabamos de señalar para las ciudades, pero si queremos
tener muy alta precisión en nuestra medida y no nos alcanza con usar
una lupa en cada extremo y amplificamos más y más los bordes, entonces
ya no vamos a ver una superficie que se interrumpe abruptamente, sino
que vamos a poder ver los átomos de la mesa, y sus nubes electrónicas
que además se van a estar moviendo porque incluso en los sólidos hay
agitación térmica.

Tenemos que preguntarnos si efectivamente podremos desprendernos de
estas incertidumbres o si podemos convivir con ellas. La distancia de
Paraná a Santa Fe nos puede servir si queremos calcular cuánto
combustible tener en el tanque (podríamos preguntarnos: ¿cuánta nafta
exactamente consume nuestro vehículo por kilómetro?), o si necesitamos
saber en cuánto tiempo podemos hacer el viaje. En el contexto de esos
problemas, que la distancia varíe en uno, dos o cinco kilómetros no
tiene demasiado impacto. Hay un grado de incertidumbre tolerable en
el conocimiento de la realidad que no afecta nuestra capacidad de
actuar sobre ella. Si queremos saber cuántas personas pueden
sentarse alrededor de la mesa, no tiene sentido tratar de obtener una
medida con la precisión de un Angstrom.

** ¿Qué preguntas puede responder la ciencia?

Muchas veces se apela al conocimiento científico para tratar de
resolver temas conflictivos, y perdemos la noción de que la ciencia no
puede responder cualquier pregunta. Pongamos por caso el tema de la
vida humana: ¿cuando comienza y cuando termina? ¿En qué momento se
inicia la existencia de un ser humano y en qué momento finaliza? Estas
preguntas también requieren criterios (compartidos y con algún grado
de arbitrariedad) para poder ser respondidas.

Lo interesante igual es advertir entonces que quizás la realidad puede
ser medida, comprendida, manipulada, pero sólo hasta cierto
punto. Quedará un borde siempre borroso, aún cuando afinemos nuestros
instrumentos de medición y nuestras teorías. Nunca la certeza podrá
ser total.

** Pragmatismo

A modo de conclusión, la condición de verdad que reina en el dominio
de la ingeniería es el pragmatismo. En tanto un instrumento o un
proceso ofrece los resultados deseados entonces resulta aceptable. En
general los desarrollos tecnológicos están orientados a resolver
necesidades, así que el desarrollo de todo lo que cumpla con la
función para lo que fue pensado resulta aceptable. No hay aquí
requerimientos de ajuste a una realidad verdadera y cognoscible, sino
la necesidad de cumplir con ciertos fines.

* Enseñanza

Como la realidad es compleja, y son complejas las teorías que usamos
para explicarla, no siempre resulta facil llegar a la verdad durante
el trayecto de enseñanza. Por ejemplo: no se puede enseñar física
partiendo de la teoría de la relatividad. Empezar por la mecánica
clásica es una elección pedagógica mucho más razonable, y de hecho es
tanta la comprensión que es posible tener del mundo con /sólo/ la
mecánica clásica que se puede ejercer la profesión sin siquiera estar
enterado de la existencia de la mecánica relativista.

Tenemos la sensación, al estudiar ciencias, por el modo en que se
presentan los conocimientos, de que las distintas disciplinas tuvieron
un progreso continuo y sus teorías conforman un cuerpo explicativo
coherente, sin fisuras. Suelen estar ausentes los problemas y
deficiencias asociados con cada teoría, no se menciona la existencia
de teorías rivales ni los conflictos asociados con ellas. En
este sentido la enseñanza es a-histórica. De esta manera, los
estudiantes (que luego se convertirán a su vez en docentes que
desconocen la historia de su disciplina) pueden llegar a tener una
percepción equivocada sobre su real conocimiento.

Otro conflicto con la verdad tiene que ver con el objetivo que se dan
para sí mismas instituciones como las facultades de ingeniería. Son
discutibles los propósitos a los cuales está orientada la
enseñanza. Más allá de los documentos oficiales y sus bienaventuradas
promesas, los profesores tratan de formar a los estudiantes para que
puedan responder a los problemas esperables en las distintas areas en
las que supuestamente son expertos. Enseñar de esta manera tiene el
peligro de cristalizar formas convencionales de actuar, repetir las
soluciones evadiendo lo que de particular tenga cada problema. Hay en
esto una especie de adoctrinamiento, un recorte a la creatividad, una
falta de compromiso con la crítica. En general pretendemos que los
estudiantes puedan afrontar tareas de diseño, producción y
mantenimiento en relación con la electrónica, instalaciones
hospitalarias, informática, fabricación de implantes, etc. La verdad
sufre en este contexto recortes porque:

a. no hay tiempo físico para formar con profundidad en tantas
especialidades distintas que conforman las carreras profesionales ni
para el abordaje de la complejidad de los temas. Pretendemos enseñar
pero lanzados en una carrera que nos deja sin aliento. Hay que cumplir
con contenidos mínimos que no son tan mínimos, y además hay una
sucesión de asignaturas que exigen de la anterior una serie de
conocimientos que provocan el abultamiento del currículum.

b. no hay mucho espacio para la creatividad, la exploración, el error,
la experimentación real y MUCHO MENOS para cuestionamientos.

c. no hay pretensión revolucionaria en la formación: el mercado de la
salud y la industria se ignoran o se toman como dados. Quizás el
problema de la salud sea resuelto mejor discutiendo políticas
alimentarias, regímenes diferentes de trabajo, modos de producción
menos contaminantes. Sin embargo, nada de esto suele aparacer.

d. si bien se promueve la idea de que el conocimiento racional es
central, la legitimación del saber proviene de la autoridad de los
profesores o de quienes evalúan a los profesores y a las instituciones
educativas.

Si miramos las industrias, las instituciones de salud públicas y
privadas, los organismos de control en los que se desempeñan los
bioingenieros, vemos que la mayoría de los egresados de la facultad
cumplen exitosamente con lo que se les pide hacer. Esto que es visto
como positivo por las autoridades de la universidad, significa también
que la formación profesional cumple en reproducir la mano de obra que
requiere el mercado: especializada, adaptada al mercado y sus
necesidades, incapaz de imaginar y motorizar cambios
significativos. Es lo razonable tratándose de una institución del
Estado.

* La insuficiencia de la verdad para la acción

La posibilidad de discernir la realidad importa para permitirnos tomar
decisiones. Esto es así tanto para todo desafío de la ingeniería como
también para nuestra vida personal y social. Necesitamos tomar
decisiones y allí el conocimiento es vital para decidir de la mejor
manera, comprendiendo los riesgos y beneficios de toda
acción. Los conocimientos científicos resultan así indispensables.

No voy a ahondar en las ventajas del conocimiento científico respecto
de la religión o cualquier otra forma de dogmatismo. Sino que me
interesa plantear las dificultades que presenta dejarse llevar por el
espejismo que del lado de la ciencia no hay más que razón. Planteo
algunos ejemplos locales:

- hace algunos años se discutió a nivel nacional y en particular en la
  UNER la llegada de fondos provenientes por ley, de la Minera La
  Alumbrera, una megamina a cielo abierto ubicada en Catamarca, de la
  cual se extrae cobre, oro y molibdeno. A pesar del rechazo social
  sustentado en diversos cuestionamientos respecto de la contaminación
  producida y sus consecuencias sobre la salud de las personas y el
  medio ambiente, si uno mira la documentación de la megaminera
  encuentra que cumple con estándares internacionales en gestión del
  medio ambiente (ISO 14001), quiere decir que hay instituciones
  prestigiosas, que con criterios supuestamente científicos, avalan el
  funcionamiento de la megaminera. Además recuerdo que contaba con el
  apoyo de instituciones vinculadas al quehacer de otros ingenieros y
  científicos, como una asociación de geólogos de tucuman y distintas
  universidades, que al día de hoy realizan visitas con alumnos de las
  carreras de Geología Minera (UBA), Higiene y Seguridad (UNTucumán),
  Recursos Naturales y Medio Ambiente (UNSalta), etc. La ciencia puede
  decir muchas cosas...

- en Entre Ríos tenemos los temas ambientales de las pasteras sobre el
  Río Uruguay, la instalación de termas, el fracking, la producción de
  transgénicos. En todos los casos aparecen especialistas,
  organizaciones, publicaciones científicas a favor y en contra,
  cuestionando los experimentos, los métodos, los resultados, las
  conclusiones.

- el caso de la soja es un ejemplo de controversia donde se advierte
  la complejidad del análisis de un problema particular. El problema
  tiene muchas aristas y no alcanza para decidir el comprenderlo
  exclusivamente desde una sola disciplina (por ejemplo a través de la
  biología celular o la embriología): se puede analizar la toxicidad
  del herbicida y llegar a conclusiones diversas y contradictorias:
  que no provoca efectos adversos en humanos, que sí los provoca aún
  frente a exposiciones ínfimas pero crónicas, que en realidad el
  glifosato actúa sobre la flora intestinal, que lo que hace daño no
  es el glifosato sino la batería de químicos que lo acompañan, que el
  problema es el gen transgénico de la soja al incorporarlo a la
  dieta, que los transgénicos hacen el mismo daño que otros alimentos,
  que otros alimentos son también transgénicos, que no se puede
  demostrar correlación entre cancer y cultivos de soja porque no se
  puede individualizar su efecto puesto que el origen de las
  patologías puede ser otro, etc. Uno podría pensar que existe una
  microverdad asociada con cada afirmación, o con cada subproblema,
  pero incluso en ese caso pueden plantearse ideas y experimentos que
  arrojarán resultados contradictorios. Es decir, se puede llegar al
  extremo de hacer trampa al diseñar los experimentos, o al analizar
  los resultados. ¿Qué dirán en este caso los empiristas? ¿Cuál será
  el experimento crucial a realizar?  Por otro lado: ¿confiaríamos en
  el juicio de uno o varios expertos para tomar decisiones?  Por
  supuesto no estoy mencionando cómo afecta a la búsqueda de la verdad
  la presencia de intereses no-científicos. Claramente aparecen
  posturas de científicos e instituciones científicas a través de las
  cuales se traslucen motivaciones e intereses personales,
  corporativos, intereses sociales, económicos, etc.

- La energía nuclear: la ciencia no puede decir si la energía nuclear es
  segura o no es segura. Sí nos puede indicar y describir algunos de
  sus riesgos y ventajas. Nos puede mostrar alternativas o la falta de
  ellas. Pero no es la ciencia la que tiene que aprobar o no
  algo. Porque cuando decimos que la ciencia aprueba o no algo lo que
  estamos diciendo es que las instituciones científicas lo hacen. Y
  como las instituciones científicas son una construcción humana
  atravesada por intereses políticos y económicos, podemos tener a los
  científicos del Conicet coincidiendo con Lino Barañao respecto de la
  inocuidad de los procesos productivos de Monsanto, Barrick Gold,
  Botnia y Chevrón.

* Conclusiones

Algunas conclusiones generales y desordenadas:

- el saber científico es limitado. La naturaleza del universo quizás
  no sea tan regular o tan definida como se suele pensar.

- lo que caracteriza al conocimiente científico no es el método sino
  la voluntad de saber a través de la razón, es la exhaustividad de la
  búsqueda.

- Es dificil pensar la ciencia aislada de las instituciones en las
  cuales se desarrolla y del contexto en el que lo hace.

- La racionalidad técnica no puede ser el único árbitro de las
  acciones humanas.

- Una ventaja respecto de otras formas de conocimiento es que evita el
  estancamiento, no se detiene, mientras que otras formas de conocer
  parecen tender a estancarse y reproducir infinitamente lo mismo.
